### ISSUE TITLE
Aqara E1 hub became unavailable after 1 or 2 days

### ISSUE THREAD

**Issue by kingwap99** [niceboygithub/AqaraGateway#101]
I have success to bridge Aqara E1 hub (aqara home app) into HA by non-falsh firmware method.
but I have two question
1. the token can only shown in telnet windows in Mihome mode not in Aqara mode
2. E1 used to work with HA only for 1 or 2 days, after that all I can do is redo and go through all the procees of hacking 

and I got the error log as below
2022-05-06 09:31:03  ERROR  gateway  Failed to connect to MQTT server 192.168.31.230 due to exception: [Errno 111] Connection refused
 2022-05-06 09:31:03  ERROR  gateway  Failed to connect to MQTT server 192.168.31.231 due to exception: [Errno 111] Connection refused
 2022-05-06 09:32:03  DEBUG  gateway  192.168.31.230: Can't read devices: telnet connection closed

![螢幕擷取畫面 2022-05-06 093750](https://user-images.githubusercontent.com/33337987/167052764-6c6340ce-9e88-4426-9b94-bf13aee07b32.jpg)
![螢幕擷取畫面 2022-05-06 032236](https://user-images.githubusercontent.com/33337987/167010351-fd76939c-b7d9-4bc7-9034-501e8f3f23f5.jpg)
![螢幕擷取畫面 2022-05-06 032304](https://user-images.githubusercontent.com/33337987/167010356-d3d69bce-4015-426d-b352-390f67391d18.jpg)
![螢幕擷取畫面 2022-05-06 031944](https://user-images.githubusercontent.com/33337987/167010357-01b3a642-c633-4b01-b5fe-03f75fab1418.jpg)

**Comment by niceboygithub** [comment]
1. no token in aqara home mode.
2. the mosquito is not running in public mode. The best way is flashing customize firmware.
