### ISSUE TITLE
Aqara door sensor can't report current state after homeassistant reboot

### ISSUE THREAD

**Issue by huayetao** [niceboygithub/AqaraGateway#102]
<img width="698" alt="iShot2022-05-15 11 02 32" src="https://user-images.githubusercontent.com/81513711/168455299-98cbc9af-ff6c-4319-9c5b-510565a331d0.png">
Aqara door sensor（t1 also included）can't report current state after homeassistant reboot，the problem will be solved after the door sensor triggered，but after restarting it appears again

**Comment by niceboygithub** [comment]
It is normal.
