### ISSUE TITLE
M1S alarm panel and RGB light are unavailable after HA upgrade to 2022.5.4

### ISSUE THREAD

**Issue by vinter-wu** [niceboygithub/AqaraGateway#104]
The HA version before the upgrade is 2021.5.x, and the M1S works fine. After the upgrade, the RGB lights and alarm panel cannot be synchronized with the Mijia APP/HOMEKIT. But switches and sensors can still be used normally. The warning record is as follows, I don't know if it is related.

 "2022-05-16 15:49:36  WARNING  gateway  Unsupported cmd: %s
 2022-05-16 15:49:36  WARNING  gateway  Unsupported cmd: %s"

**Comment by niceboygithub** [comment]
Please update to master branch for test first. It will be release soon if no other bugs.
