### ISSUE TITLE
[Question] Use other temperature sensor as thermostat current temperature 

### ISSUE THREAD

**Issue by bluefoxlee** [niceboygithub/AqaraGateway#108]
Some Xiaomi/Aqara thermostat/companion comes with build-in temperature sensor and some don't (like P Series). 
You could assign temperature sensor for those companion with Home Assistant intergration.

Wonder is it possible to use other temperature sensor as thermostat (like S1/S2) current temperature with customize config, since the temperature might not accurate due to the control panel installation position.

**Comment by niceboygithub** [comment]
what are the model of thermostats?

**Comment by bluefoxlee** [comment]
> what are the model of thermostats?

lumi.ctrl_hvac.es1, KTWKQ01ES added by manual. It works ok with a minor issue so far.
And going to close this issue since it seems customize.yal might be a work around solution.
