### ISSUE TITLE
Why M1s cannot download mosquitto with command

### ISSUE THREAD

**Issue by qiyell** [niceboygithub/AqaraGateway#111]
Why M1s cannot download mosquitto with /data/bin/curl -s -k -L -o /data/bin/mosquitto https://raw.githubusercontent.com/niceboygithub/AqaraM1SM2fw/main/binutils/mosquitto

**Comment by a000a498** [comment]
/data/scripts # cd /data/bin
/data/bin # wget -O /data/bin/curl "http://master.dl.sourceforge.net/project/mgl03/bin/curl?viasf=1"
Connecting to master.dl.sourceforge.net (216.105.38.12:80)
curl                 100% |***********************************************************************|  2271k  0:00:00 ETA
/data/bin # chmod +x /data/bin/curl
/data/bin # /data/bin/curl -s -k -L -o /data/bin/mosquitto https://raw.githubusercontent.com/niceboygithub/AqaraM1SM2fw/main/binutils/mosquitto
/data/bin/curl: line 1: syntax error: unexpected "("

**Comment by niceboygithub** [comment]
If your M1S is 2022 version, it is different from old M1S.
And AqaraGateway do not support M1S 2022.

**Comment by a000a498** [comment]
M1S 2022 cannot Flash?

**Comment by niceboygithub** [comment]
> M1S 2022 cannot Flash?

yes, but for why and what purpose?

**Comment by a000a498** [comment]
> > M1S 2022 cannot Flash?
> 
> yes, but for why and what purpose?

I mean M1S 2022 cannot enable telnet then Integrate to HA?

**Comment by niceboygithub** [comment]
You can enable the telnet of M1S 2022 but you cannot integrate to HA.
M1S 2022 did not use mqtt to send/recv the message of zigbee.

**Comment by a000a498** [comment]
> You can enable the telnet of M1S 2022 but you cannot integrate to HA. M1S 2022 did not use mqtt to send/recv the message of zigbee.

I see, so what device I can integrate to HA now? M2, M1S, 2021, P3, G2, G2H, G3, E1?

**Comment by niceboygithub** [comment]
M1S CN (old one, not 2022), P3 CN, M2 CN, H1 CN, E1 CN, G3 CN, G2H Pro CN, G2H CN were verified OK.
