### ISSUE TITLE
Can you update new firmware for H1 hub

### ISSUE THREAD

**Issue by fuxy1999** [niceboygithub/AqaraGateway#113]
Hi！
How about update the firmware for H1.
My H1 hub is work on 3.4.0_0004.0617.
It’s too new then your firmware
 Thank you

**Comment by niceboygithub** [comment]
Can you provide the  firmware download url?

**Comment by rezmus** [comment]
https://cdn.aqara.com/cdn/opencloud-product/mainland/product-firmware/prd/lumi.gateway.sacn01/20220330145055_lumi.gateway.sacn01_AIOT_V3.4.0_0004.0617_20220329_981e0a.bin

**Comment by th3weird0** [comment]
> https://cdn.aqara.com/cdn/opencloud-product/mainland/product-firmware/prd/lumi.gateway.sacn01/20220330145055_lumi.gateway.sacn01_AIOT_V3.4.0_0004.0617_20220329_981e0a.bin

Btw ,how do you get that resource url bro?use Wireshark to capture http request or something?
