### ISSUE TITLE
请教下那个G3固件3.3.4怎么提取？

### ISSUE THREAD

**Issue by haoyixiu** [niceboygithub/AqaraGateway#117]

**Comment by niceboygithub** [comment]
You can 7z to extract the fw file.

Find the fw file from my another repo .

**Comment by JachinY** [comment]
是直接把20211216200913_lumi.camera.gwpagl01_AIOT_V3.3.4_0007.0004_20211216_28f9c3.bin拷入SD卡还是将其更名为rootfs.bin再拷入呢？我尝试过将其更名之后拷入，按照您的流程操作之后，G3的LED并没有亮红灯
