### ISSUE TITLE
p3一直提示安装错误

### ISSUE THREAD

**Issue by whowho182** [niceboygithub/AqaraGateway#121]
![image](https://user-images.githubusercontent.com/49549058/187013345-88c46ff5-c251-4322-a737-708ca530d255.png)
Home Assistant 2022.9.0.dev20220729
前端版本： 20220729.0.dev - latest
gateway3中有信息Name: Aqara Air Conditioning Controller P3
Model: lumi.aircondition.acn05
IP: 192.168.1.202
MAC: 54:EF:44:29:A9:1B
Token: 744c6b54726e74534252466979666444
一直报错，装不上这个网关，请教一下那里问题

**Comment by niceboygithub** [comment]
After HA 2022.9.0 released, I will check it. Please stay tuned.
