### ISSUE TITLE
add support Aqara L1-350 Ceiling Light lumi.light.acn003

### ISSUE THREAD

**Issue by jwxa** [niceboygithub/AqaraGateway#122]
is there anything else you want?

{
    # light with brightness and color temp
    'lumi.light.acn003': ["Aqara", "Aqara L1-350 Ceiling Light", "ZNXDD01LM"],
    'mi_spec': [
        ['2.1', 'power_status', 'light', 'light'],
        ['2.2', 'light_level', 'brightness', None],
        ['2.3', 'colour_temperature', 'color_temp', None],
    ]
},

![image](https://user-images.githubusercontent.com/9533487/187033276-e0311833-b71d-46fa-8dd1-c14840db1dc7.png)

**Comment by niceboygithub** [comment]
Does it work in Mi Home app?

**Comment by jwxa** [comment]
Yes, light status in the mi home will change synchronously
