### ISSUE TITLE
M1S 2022 (lumi.gateway.acn004) receives no response when adding integrations

### ISSUE THREAD

**Issue by q3ccn** [niceboygithub/AqaraGateway#126]
After submitting the config, Aqara Gateway responses nothing and close. Where should I found the logs? 
![image](https://user-images.githubusercontent.com/3367273/196018382-1d6a546b-146f-434e-b840-d69827cb678a.png)
![image](https://user-images.githubusercontent.com/3367273/196018419-02cf32af-e541-4fa3-9fc5-6c02260cb7ab.png)

Gateway info:
Name: Aqara Hub M1S 2022
Model: lumi.gateway.acn004
IP: 192.168.0.4
MAC: 54:EF:44:**:**:**
Token: 426f6c333768423567476a6f4574****
fw version: 4.0.2_0006

ha info:
Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.10.0
Kernel version 4.19.0-22-amd64
Agent version 1.2.2

Thanks for answering.

**Comment by niceboygithub** [comment]
M1S 2022 is not in support list

**Comment by q3ccn** [comment]
Thanks for answering.
Will it be supported in the future?

**Comment by niceboygithub** [comment]
No, it doesn’t use mqtt. Can not be supported.
