### ISSUE TITLE
G3 PTZ Problem

### ISSUE THREAD

**Issue by 5eeT0uc4** [niceboygithub/AqaraGateway#128]
Hello. 

I'm found that PTZ stop to work in Aqara app after entering following commands

chmod a+w /data/scripts/post_init.sh
echo -e "#!/bin/sh\n\nasetprop sys.camera_ptz_moving true\nfw_manager.sh -r\nfw_manager.sh -t -k" > /data/scripts/post_init.sh
chattr +i post_init.sh

Help me please turn on PTZ control in Aqara app

**Comment by niceboygithub** [comment]
which version of firmware you are using?

I did not have problem with firmware 3.3.9.

**Comment by amaisano** [comment]
I had the same issue. PTZ no longer worked in Aqara with FW 3.3.4.

I do not know where FW 3.3.9 is.

**Comment by weising26** [comment]
@niceboygithub i thought 3.3.9 cannot open telnet? i also having same problem on 3.3.4
