### ISSUE TITLE
How to disable  gateway IPv6?

### ISSUE THREAD

**Issue by superman110** [niceboygithub/AqaraGateway#129]
When the G3 gateway has IPv6, the connection mqtt will use IPv6, causing the gateway to be offline. How can I disable the IPv6 function of the G3 gateway independently without closing the upper level router to assign IPv6 to the entire LAN?
![2022-10-22 212658](https://user-images.githubusercontent.com/1772988/197342030-f83153c1-b690-46b1-a5e9-2a3e124e39da.jpg)

**Comment by niceboygithub** [comment]
gateway did not support IPv6.
