### ISSUE TITLE
Zigbee2Mqtt

### ISSUE THREAD

**Issue by b6mh3** [niceboygithub/AqaraGateway#13]
Any chances to enable the Z2M function like the mgl03_fw topic?

**Comment by niceboygithub** [comment]
It is possible on M1S.
But I do not recommend it. But you have a better one, mgl03.
mgl03 is cheaper. Also, it supports BlueTooth when z2m function is enabled.

**Comment by b6mh3** [comment]
> It is possible on M1S.
> 
> 
> 
> But I do not recommend it. Because you have a better one, mgl03.
> 
> mgl03 is cheaper. Also, it supports Alex enhanced BlueTooth function when z2m function is enabled.
> 
> 

It's a nice comment...looks like the mgl03 is the best choice if we want to integrate everything. Will try to get one, tks!
