### ISSUE TITLE
Unlock G3 Update

### ISSUE THREAD

**Issue by 5eeT0uc4** [niceboygithub/AqaraGateway#130]
Hello

How to unlock G3 update after locking. 

I'm putted this commands to lock the firmware update process

```
mkdir -p /data/ota_dir
touch /data/ota_dir/lumi_fw.tar
chattr +i /data/ota_dir/lumi_fw.tar
```

I cant delete directory
`rm: can't remove 'lumi_fw.tar': Operation not permitted`

Thank you

**Comment by niceboygithub** [comment]
chattr -i /data/ota_dir/lumi_fw.tar
