### ISSUE TITLE
can't get Aqara M1S working on HomeAssistant

### ISSUE THREAD

**Issue by sator86** [niceboygithub/AqaraGateway#133]
Hello,
I have followed all steps, now Telnet is enabled even after reboot,
I can get access to CLI mode

however, when I install aqara gateway on HA, it's asking me IP, token .. which I fill correctly
but, after a while, I have look like it's added, but nowhere I can find aqara, seems that it's not added
I search on logs, nothing 
can you help me please 
thank you

filling the informations
![Capture d’écran 2022-11-10 à 17 41 02](https://user-images.githubusercontent.com/55639966/201156064-59b338b9-e62c-49a4-b320-d6ce30bd8395.png)

looks like a confirmation that's ok, but it was not added
![Capture d’écran 2022-11-10 à 17 44 16](https://user-images.githubusercontent.com/55639966/201156104-1b4da206-811d-403d-9efb-00931f62da79.png)

**Comment by sator86** [comment]
seems that something is wrong with the files, looks like not compatible

/data # ./socat 
./socat: line 1: syntax error: unexpected "("

I had the same issue with mosquitto

any idea ?

**Comment by niceboygithub** [comment]
You use wrong binaries.
M1S is mipsel SoC.

**Comment by sator86** [comment]
this is on my M1S

/ # cat /proc/cpuinfo 
processor       : 0
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 12.00
Features        : half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 1
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 12.00
Features        : half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

Hardware        : SStar Soc (Flattened Device Tree)
Revision        : 0000
Serial          : 0000000000000000

**Comment by niceboygithub** [comment]
M1S 2022 is not supported.

**Comment by sator86** [comment]
thank you for your help
any chance to be supported in the future ?

**Comment by Jens-Wymeersch** [comment]
@niceboygithub Please let also me know when it will be supported

**Comment by kyc1338** [comment]
I installed M1S gateway to HA successfully but no device shown. Please advise what would cause the problem?
![config](https://user-images.githubusercontent.com/33945816/223906508-a3f20b0c-3fd6-41b9-8c17-2ad043c96d23.png)
![success](https://user-images.githubusercontent.com/33945816/223906525-9e202f65-27e2-4a1d-94ab-c6757d18db64.png)
![result](https://user-images.githubusercontent.com/33945816/223906562-5da44dfc-371b-4891-89ab-1da969cc08fd.png)
