### ISSUE TITLE
Please Update for Hub M2

### ISSUE THREAD

**Issue by ductu3590** [niceboygithub/AqaraGateway#134]
Thank you for developing this app.  However, it would be nice to be able to use it without having to do the operations (flash filmwave, open the tenlet port, etc.), which makes it difficult for new users.  Looking forward to the update for Aqara Hub M2, can I wait???

**Comment by niceboygithub** [comment]
Due to my limited ability, I do not have solution to enable telnet without flash firmware.
Maybe other experts can have solution someday.
