### ISSUE TITLE
AQARA G2H ZNSXJ12LM telnet activation

### ISSUE THREAD

**Issue by hepf68** [niceboygithub/AqaraGateway#138]
Hi guys, 

Is there any way to activate the telnet on AQARA G2H ZNSXJ12LM with firmware 2.2.7_0001.0618?

I already tried the file on ssd card but it does not working.

Can you help me?
hepf68

**Comment by isra60** [comment]
I can confirm you in 2.2.6 is it working.

Assure you save the hostname file with unix type on notepad ++. Also it takes a litte to start the telnet. So you must wait about 5 min

**Comment by isra60** [comment]
Also. Does anyone know if I need to add the token for a G2H camera? That should be clarify. AFAIAK is not possible to add this camera to Xiaomi Home app and extract the token. 
I have problems trying to add the camera to HA. Everything seems to be ok inside the camera related to public mosquitto
How to check the logs for this integration related to trying to connect with the telnet camera?

**Comment by evripidis** [comment]
> Also. Does anyone know if I need to add the token for a G2H camera? That should be clarify. AFAIAK is not possible to add this camera to Xiaomi Home app and extract the token. I have problems trying to add the camera to HA. Everything seems to be ok inside the camera related to public mosquitto How to check the logs for this integration related to trying to connect with the telnet camera?

Did you had any chance with that? I'm on the same page as you and it is not working

**Comment by isra60** [comment]
Yeah. I finally solved with this

On shell.py

```
class TelnetShellG2H(TelnetShell):

    def login(self):
        """ login function """
        self._aqara_property = True

        self.write(b"\n")
        self.read_until(b"login: ", timeout=10)

        password = self._password
        if ((self._password is None) or
            (isinstance(self._password, str) and len(self._password) <= 1)
        ):
            password = '\n'

        self.write(b"root\n\r")
        if password:
            self.read_until(b"Password: ", timeout=3)
            #self.write(password.encode() + b"\n")
            self.run_command(password)

        self.run_command("stty -echo")
        **self.read_until(b"/ # ", timeout=10)**
        self._suffix = "# "

```

**Comment by c20h32o5** [comment]
> Hi guys,
> 
> Is there any way to activate the telnet on AQARA G2H ZNSXJ12LM with firmware 2.2.7_0001.0618?
> 
> I already tried the file on ssd card but it does not working.
> 
> Can you help me? hepf68

Hi. I need dump rootfs.bin European region version 2.2.7. Help me?
