### ISSUE TITLE
unsupported modell: lumi.switch.n2acn1

### ISSUE THREAD

**Issue by miniknife88** [niceboygithub/AqaraGateway#14]
Aqara Double Wall Switch H1 PRO
model: lumi.switch.n2acn1 [QBKG31LM]

Has the same function as Aqara Double Wall Switch D1，try to add:

`{
    'lumi.switch.b2lacn02': ["Aqara", "Double Wall Switch D1", "QBKG22LM"],
    'lumi.switch.b2laus01': ["Aqara", "Double Wall Switch US", "WS-USC02"],
    'lumi.switch.n2acn1': ["Aqara", "Double Wall Switch H1 PRO", "QBKG31LM"],
    'params': [
        ['4.1.85', 'channel_0', 'channel 1', 'switch'],
        ['4.2.85', 'channel_1', 'channel 2', 'switch'],
        ['13.1.85', None, 'button_1', None],
        ['13.2.85', None, 'button_2', None],
        ['13.5.85', None, 'button_both', None],
        [None, None, 'switch', 'binary_sensor'],
    ]
}`

**Comment by miniknife88** [comment]
unsupported modell: lumi.light.cbacn1
Aqara LED Controller T1
model: lumi.light.cbacn1 [HLQDQ01LM]

Only brightness adjustment，try to add:

`{
    # light with brightness
    'ikea.light.led1623g12': ["IKEA", "Bulb E27 1000 lm", "LED1623G12"],
    'ikea.light.led1650r5': ["IKEA", "Bulb GU10 400 lm", "LED1650R5"],
    'ikea.light.led1649c5': ["IKEA", "Bulb E14", "LED1649C5"],  # tested
    'lumi.light.cbacn1': ["Aqara", "LED Controller T1", "HLQDQ01LM"],
    'params': [
        ['4.1.85', 'power_status', 'light', 'light'],
        ['14.1.85', 'light_level', 'brightness', None],
    ]
}`

**Comment by miniknife88** [comment]
unsupported modell: lumi.switch.rkna01
Aqara Smart Knob Switch H1
model: lumi.switch.rkna01 [ZNXNKG01LM]

It has the same function as Smart Knob H1 and comes with three relays，try to add:

`{
    'lumi.switch.rkna01': ["Aqara", "Smart Knob Switch H1", "ZNXNKG01LM"],
    'params': [
        ['0.12.85', 'load_power', 'power', 'sensor'],
        ['0.13.85', None, 'consumption', 'sensor'],
        ['4.1.85', 'channel_0', 'channel 1', 'switch'],
        ['4.2.85', 'channel_1', 'channel 2', 'switch'],
        ['4.3.85', 'channel_2', 'channel 3', 'switch'],
        ['13.1.85', None, 'button', None],
        [None, None, 'switch', 'binary_sensor'],
    ]
}`

**Comment by miniknife88** [comment]
lumi.switch.rkna01  The name is the same as Aqara Smart Knob H1：[Smart Knob Switch H1]

The entities of the three switches are not displayed

**Comment by niceboygithub** [comment]
already try to fix.
Please test the latest commit
