### ISSUE TITLE
M1s gateway not reconnecting to router after router reboot

### ISSUE THREAD

**Issue by shummo** [niceboygithub/AqaraGateway#156]
M1s gateway not reconnecting to router after router reboot.
If i restart the router I have to manually replug the hub to connect back to router. Until that, i can't do anything with the hub.

Maybe is there any way to tell /force the gateway rebooting every day for example at 8:05?

**Comment by niceboygithub** [comment]
The better solution is that use fixed ip for the gateway, you can configure it in your router.
