### ISSUE TITLE
m1s_update.sh：./m1s_update.sh: line 788: getprop: not found

### ISSUE THREAD

**Issue by xorxorxorxor** [niceboygithub/AqaraGateway#165]
# Device Info
Name: Aqara Hub M1S 2022
Model: lumi.gateway.acn004

# Reproduce
1. I have telneted the gateway with empty password,but the login name is root instead of admin.
2. when I run the /m1s_update.sh
![image](https://user-images.githubusercontent.com/44894066/217013315-fabae49c-37c5-4bf4-a33b-a14fcbb5fbea.png)
3. Besides, the curl downloaded from http://master.dl.sourceforge.net/project/mgl03/bin/curl?viasf=1 cannot be executed correctly,it showed the following result:
![image](https://user-images.githubusercontent.com/44894066/217013831-a8a38add-dbd5-42b6-a817-ad2c90e548ff.png)
4. And I tryed the curl downloaded from "http://master.dl.sourceforge.net/project/aqarahub/binutils/curl?viasf=1,and it can run correctly.
![image](https://user-images.githubusercontent.com/44894066/217014239-87bdaeca-4c32-4468-95d3-57a62e0832c4.png)
# How can I solve the problem? 
Thank you very much!

**Comment by niceboygithub** [comment]
M1S 2022 is not supported.

**Comment by wangjm9** [comment]
Will the next version support M1S 2022?

**Comment by niceboygithub** [comment]
Nope

**Comment by wangjm9** [comment]
regret  :(
