### ISSUE TITLE
G2H Pro telnet logged failed

### ISSUE THREAD

**Issue by Faultiness** [niceboygithub/AqaraGateway#173]
Hi,

I'm using G2H Pro (ZNSXJ15LM) with firmware 3.3.4_0016.0004. I've enabled telnet access using [aQRootG3](https://github.com/Wh1terat/aQRootG3). And I've also enabled mqtt with:
```
mkdir /data/bin
cd /data/bin
wget -O /tmp/curl "http://master.dl.sourceforge.net/project/aqarahub/binutils/curl?viasf=1"; chmod +x /tmp/curl
/tmp/curl -s -k -L -o /data/bin/mosquitto https://raw.githubusercontent.com/niceboygithub/AqaraCameraHubfw/main/binutils/mosquitto_e1; chmod a+x /data/bin/mosquitto
```

The HASS is running in Docker with `--network=host` and I can connect to the camera using `telnet` on the host.
![图片](https://user-images.githubusercontent.com/12472447/225012423-d7bdda81-8862-4ece-b76e-f638b0b881f1.png)

However, the status in the system_health suggests HASS cannot connect to the camera via telnet while mqtt is ok:
![图片](https://user-images.githubusercontent.com/12472447/225012738-8721b3bb-8436-4296-b755-14c7aa9dfc3f.png)

I've tried to reboot the camera and HASS docker and reload AqaraGateway but useless. The log of HASS that may relate to this issue is:
![图片](https://user-images.githubusercontent.com/12472447/225013848-325904a4-72a1-47ce-b436-54947029b564.png)

I've tried to change line 44, `timeout=10` to a larger one, say 30. But still not working.

May I ask what could be the reason for this? And how should I fix it? Thanks to anyone with suggestions.

**Comment by Faultiness** [comment]
Update:
The error happened on line 44, which is the login part belonging to `TelnetShell` class, not `TelnetShellG2HPro`. Failed to login due to different login methods. I copied the `login()` part from `TelnetShellG3` and replaced then it works fine.
![图片](https://user-images.githubusercontent.com/12472447/225101358-0af3434b-b5f2-41d0-9c79-bced8ec1ea2b.png)
And then:
![图片](https://user-images.githubusercontent.com/12472447/225102438-7fcc7ff9-11ac-4bf9-b86d-6b8b0aaf5e48.png)

ps:
The device name of my gateway is `lumi.camera.agl001`, which matches the config in `aqara_gateway/core/utils.py`:
![图片](https://user-images.githubusercontent.com/12472447/225102272-5354bb17-3e6c-4e7f-89e8-c8e5b3c7bf53.png)
![图片](https://user-images.githubusercontent.com/12472447/225102554-51984400-b20e-4584-9b74-b07b06c182f2.png)

**Comment by roben123** [comment]
[https://user-images.githubusercontent.com/41981098/239699389-62d29a30-3193-4cfd-8ef8-c677632621ad.jpg](url)

**Comment by roben123** [comment]
可以给我你的QQ或者VX吗？ 我想请教你，感谢！

**Comment by niceboygithub** [comment]
The telnet login was imporoved in 0.2.4. Please have a try.
