### ISSUE TITLE
M2 EU with modified firmware

### ISSUE THREAD

**Issue by Mq93** [niceboygithub/AqaraGateway#178]
I was able to flash M2 EU with modified firmware (https://github.com/niceboygithub/AqaraM1SM2fw/issues/50). I can confirm that telnet is working. I also ran the m2_update.sh (https://github.com/niceboygithub/AqaraM1SM2fw/issues/50#issuecomment-1249973058) 

However, when I try to add aqara gateway integration after adding host IP it starts loading then empty dialog screen comes: 
![image](https://user-images.githubusercontent.com/132373397/235700352-cbf853ce-89cd-4be8-b054-f607350b4eeb.png)

Homeassistant logs also show no information. No devices/integration show after the dialog box.

Any help is appreciated.

**Comment by niceboygithub** [comment]
What is the model of your Hub?

**Comment by Mq93** [comment]
Model is HM2-G01 
SKU is AG035EUB01

**Comment by niceboygithub** [comment]
another model number
Telnet then enter the command after log in
'''
agetprop |grep model
'''

**Comment by Mq93** [comment]
It is 
lumi.gateway.iragl5

**Comment by niceboygithub** [comment]
iragl5 shall be CN version. It shall works well.

**Comment by Mq93** [comment]
“getprop | grep lumi.gateway” gives:

[persist.sys.model]: [lumi.gateway.agl001]
[ro.sys.model]: [lumi.gateway.iragl5]

When I run m2_update.sh from your repo it shows that model is unsupported but other one from https://github.com/niceboygithub/AqaraM1SM2fw/issues/50#issuecomment-1249973058 is okay.

I am not sure how to proceed / if this model is supported

**Comment by niceboygithub** [comment]
agl01 is not CN version.
m2_update.sh does not support agl01.

If you can use AqaraGateway.exe to flash and boot up without problem after flashed, it means that the M2 uses new flash and the firmware was not signed.

You can add the model to "utils.py"

**Comment by Mq93** [comment]
Added it to devices in utils.py and now it works. 

Thank you for your help.

**Comment by shift-del1** [comment]
@Mq93: after flashing thebM2 EU with the unsigned Chinese firmware, which server you can connect the hub to? Which region is available for the accessories? Can you use Aqara Home, Apple Home (through Apple Homekit) and Home Assistant (through telnet) at the same time? Thank you.

**Comment by FastFreddi** [comment]
> 

How do you add agl001 to utils.py? Is it a file on the device accessed through telnet?

**Comment by FastFreddi** [comment]
Figured it out, its in home assistant folder and now it works
