### ISSUE TITLE
g2h pro Firmware 3.3.4

### ISSUE THREAD

**Issue by roben123** [niceboygithub/AqaraGateway#179]
hello bro , could you provide 3.3.4 firmware with G2H Pro ? thanks !

**Comment by niceboygithub** [comment]
Why you need the version 3.3.4 firmware?

**Comment by roben123** [comment]
https://github.com/Wh1terat/aQRootG3#warningwarning-warning

because i wanna do this

**Comment by roben123** [comment]
my firmware is the latest ， so i wanna flash the Firmware 3.3.4 , open telnet

**Comment by niceboygithub** [comment]
Check another repo AqaraCametaHubfw

**Comment by roben123** [comment]
thanks bro your provide !

i have new question：how the g2h pro downgrade the firmware ?

There is G3 downgrade the firmware ：

https://github.com/niceboygithub/AqaraGateway
1. Get 'rootfs.bin' of firmware version 3.3.4. (use 7z to extract the firmware bin)
2. Copy 'rootfs.bin' to sdcard which is using FAT32 format.
3. Power Off G3.
4. Insert the sdcard to G3.
5. Press the front button of G3.
6. Power on G3.
7. Wait three seconds and release the button.
8. If the LED is turned to RED, it starts to flash 'rootfs.bin'.

**Comment by niceboygithub** [comment]
Same method

**Comment by roben123** [comment]
Dear bro , i have successed downgrade 3.3.4_0014.0004 .
i connect to telnet , but show this , maybe need 3.3.4_0010.0004 ?
![Snipaste_2023-05-21_00-43-42](https://github.com/niceboygithub/AqaraGateway/assets/41981098/62d29a30-3193-4cfd-8ef8-c677632621ad)

**Comment by roben123** [comment]
rtsp also could not connect

**Comment by roben123** [comment]
Dear bro , i try port：8554 ，NAS use account & password to login , could not connect rtsp , i dont know why .  the reason is RTSP unavailable ?

**Comment by niceboygithub** [comment]
If you see the prompt "#", it is ok.

And the rtsp is not running as default.

**Comment by roben123** [comment]
> If you see the prompt "#", it is ok.
> 
> And the rtsp is not running as default.

someone said use to enable rtsp ：rtsp >/dev/null 2>&1 &

i try it but still failed ，bro，do you have any advice ？

**Comment by niceboygithub** [comment]
What you mean with failed?

The rtsp url can be get by the command

'''
agetprop |grep rtsp_url
'''

**Comment by roben123** [comment]
> 
![Snipaste_2023-05-21_23-20-21](https://github.com/niceboygithub/AqaraGateway/assets/41981098/121e0fea-1b8e-4238-af64-8897ff95e344)

the port is 8554 ？

"What do you mean with failed?"
i use synology NAS to connect the g2h pro with rtsp , but show need account and password , i try my Aqara account ID and password , failed , i dont know why.

**Comment by roben123** [comment]
![Snipaste_2023-05-21_23-24-25](https://github.com/niceboygithub/AqaraGateway/assets/41981098/ec437fb3-b8ea-408f-9866-e06fdda95c3b)

i use my Aqara account and password , but failed , use username "root"  and password empty , also failed , i dont know what is the real account and password .

**Comment by niceboygithub** [comment]
The username and password are randomly generated.

Use "agetprop sys.camera_rtsp_url" to get detail.

**Comment by roben123** [comment]
> 所有者

thanks bro , success!

**Comment by roben123** [comment]
![Snipaste_2023-05-21_23-41-40](https://github.com/niceboygithub/AqaraGateway/assets/41981098/c89ab4d7-c6b2-4fba-ad7f-4df8cfe08381)
Thanks bro !

**Comment by roben123** [comment]
> And the rtsp is not running as default.

Dear bro , how to make camera rtsp auto running when restart ?

**Comment by niceboygithub** [comment]
create the post_init.sh scripts

```
mkdir -p /data/scripts
vi /data/scripts/post_init.sh
chmod a+x /data/scripts/post_init.sh
```

The content of post_init.sh
```
#!/bin/sh

/data/bin/mosquitto -d
asetprop sys.camera_ptz_moving true

fw_manager.sh -r
fw_manager.sh -t -k

cp /bin/app_monitor.sh /tmp; sed 's/ rtsp \-a / rtsp /g' -i /tmp/app_monitor.sh
killall -9 app_monitor.sh; /tmp/app_monitor.sh &
killall rtsp
[ -x /data/bin/connectivity.sh ] && /data/bin/connectivity.sh &
```

**Comment by wizardofozzie** [comment]
> Same method

@niceboygithub 

What does it look like with G2H Pro (as lights are different)?

How would I test this has completed successfully on G2H Pro?

Can confirm it works on G3

https://cdn.aqara.com/cdn/website/mainland/static/docs/User-Maunal_G2H-Pro.pdf

```
Indicator Light Status              Status Description 

Yellow light is on steady          The camera is turning on
Yellow light flashes quickly      Waiting to connect to the network
Yellow light flashes slowly       The camera is being resetting/OTA upgrading
Blue light flashes quickly        Connecting to the network
Blue light flashes slowly          Connected to the network successfully and the account is being bound 
Blue light is on steady             Working properly
Red light is on steady              Live video is in progress
White light is on steady           No network is connected in 10 minutes after starting
Purple light flashes slowly      Accessories are allowed to be added
Off                                             The indicator is turned off/the device sleeps/the device is not powered
```

**Comment by wizardofozzie** [comment]
> Same method

You said `rootfs.bin`, but inside the bin is `rootfs.sqfs`. Should it be renamed to `rootfs.bin` and then put on SD and booted with instructions as above? I'm struggling to get it to work

**Comment by Write** [comment]
> create the post_init.sh scripts
> 
> ```
> mkdir -p /data/scripts
> vi /data/scripts/post_init.sh
> chmod a+x /data/scripts/post_init.sh
> ```
> 
> The content of post_init.sh
> 
> ```
> #!/bin/sh
> 
> /data/bin/mosquitto -d
> asetprop sys.camera_ptz_moving true
> 
> fw_manager.sh -r
> fw_manager.sh -t -k
> 
> cp /bin/app_monitor.sh /tmp; sed 's/ rtsp \-a / rtsp /g' -i /tmp/app_monitor.sh
> killall -9 app_monitor.sh; /tmp/app_monitor.sh &
> killall rtsp
> [ -x /data/bin/connectivity.sh ] && /data/bin/connectivity.sh &
> ```

FYI this breaks HomeKit movement detection. The movement detector stays as always detecting something.
For now my file look like this and it works :

```
#!/bin/sh

fw_manager.sh -r
passwd -d $USER
fw_manager.sh -t -k

pkill rtsp
rtsp &
```
