### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by omerf111** [niceboygithub/AqaraGateway#18]
"Then install this integration by HACS. After installation, add this componment via GUI integration of Home Assistant. "

is something missing in here?

**Comment by niceboygithub** [comment]
after installed, need restart HA.

**Comment by niceboygithub** [comment]
> i mean which integration and componment? i did get the token but i'm confused about what to do next.


Install this integration by [**HACS**](https://hacs.xyz/). Add this component "https://github.com/niceboygithub/AqaraGateway" that you are issuing.

Example from Alex's Xiaomi Gateway 3
https://github.com/AlexxIT/XiaomiGateway3#install
https://github.com/AlexxIT/XiaomiGateway3#config

> i can't open the telnet command with these instructions because i don't know what to do with php-miio-v.0.2.6.

As README say it is "OR" , "...add this component via GUI integration of Home Assistant. **Or** you can use custom open telnet command  ..."
If you have input "token", you don't need to manually enable telnet.  
The instructions to enable telnet in "https://gist.github.com/zvldz/1bd6b21539f84339c218f9427e022709" are detailed description. If you want to enable telnet manually, please read again.

**Comment by InsaneWookie** [comment]
I've created some instructions for the process I went thought to get my M1S working with Home Assistant 
Hopefully this is useful 
https://gist.github.com/InsaneWookie/1221cd6267745ea3c16f6a2a83ba3a44

**Comment by omerf111** [comment]
Thank you for both of you. I Will try it when i got time.

**Comment by omerf111** [comment]
I'm tryin to add gateway via this component but, i get this massage "Unknown error occurred". Does the device need to be in china server? I'm using on international server.

**Comment by InsaneWookie** [comment]
Have you extracted the TOKEN?
I think the region is only needed for discovery within the Xiaomi app (which is then allows you to extract the TOKEN)

**Comment by omerf111** [comment]
Thank you, I'm really dumb about these programs. i did install the library but i don't know where to put this command. I'm researching but nothing pops. and i have a big problem, because i'm working with this (wrong ways) the automations i set on mi home app dissapered. i can't control them anymore.

**Comment by InsaneWookie** [comment]
You want to run that command where you installed the python-miio library (ie if you installed it on you laptop, that's where you will want to run it) And replace the `<gateway_ip>` with the ip of your Aqara Gateway and `<gateway_token>` with the token you extracted previously

**Comment by niceboygithub** [comment]
I already the improve the configuration.
Just install by HACS and add integration in UI config (just need token) if use gateway in Mi home mode. That's it.
