### ISSUE TITLE
Aqara Hub E1 can display the device, but the status is completely unknown

### ISSUE THREAD

**Issue by bugensui2022** [niceboygithub/AqaraGateway#182]
Aqara Hub E1 can display the device, but the status is completely unknown，I want to know where the problem is and how I can solve it
![1](https://github.com/niceboygithub/AqaraGateway/assets/108134797/d4b67aa3-8d75-4458-9e15-a137bd967d96)
![2](https://github.com/niceboygithub/AqaraGateway/assets/108134797/2f54d39d-c880-41dc-804a-12d11664d8dd)
![3](https://github.com/niceboygithub/AqaraGateway/assets/108134797/3f6337fe-679c-4767-912a-d23451596776)

**Comment by 9runner** [comment]
same here, actually I have upgrade to the most latest version of the customized firmware already

**Comment by haoyang324** [comment]
Possible reason: Failed to connect to MQTT server xxx due to exception: [Errno 111] Connection refused

To run the service with the system, you must create an empty file with one or some of the names

/data/enable_mosquitto
