### ISSUE TITLE
Unable to add aqara p3

### ISSUE THREAD

**Issue by Plaudern** [niceboygithub/AqaraGateway#183]
Firmware version 4.0.1_0004，I have obtained the ip and token through xiaomi gateway 3, but when adding it, it prompts Unknown error occurred

**Comment by niceboygithub** [comment]
The set_ip_info was removed.

Please see this post.
https://github.com/AlexxIT/XiaomiGateway3/issues/1057#issuecomment-1543550411

**Comment by nuo-git** [comment]
> Firmware version 4.0.1_0004，I have obtained the ip and token through xiaomi gateway 3, but when adding it, it prompts Unknown error occurred

Have you found the way out? THX
