### ISSUE TITLE
M1S(ZHWG15LM)出现了添加网关就死机的问题，需要手动重启。米家固件为出厂自带版本4.0.1.0002

### ISSUE THREAD

**Issue by PerryLayne** [niceboygithub/AqaraGateway#186]
与[#120 ](https://github.com/niceboygithub/AqaraGateway/issues/120)问题锁描述的完全一致。但版本号不同
非M1S 2022版，我的M1S生产日期是2023.03   难道新出厂的就做了限制吗？

我看#120说降级到4.0.1_0026解决，但比4.0.1.0002的新的能用，难道更旧不能用吗？

我在想有没有可能更改了硬件或者固件之类的，不敢去尝试，希望有好的解决方式。

我并没有找到日志在哪里，如果需要的话我可以提交

**Comment by PerryLayne** [comment]
![Snipaste_2023-07-06_02-56-36](https://github.com/niceboygithub/AqaraGateway/assets/95447044/c21b93c1-6be6-452f-88db-c95dc6cd4049)
![Snipaste_2023-07-06_02-58-43](https://github.com/niceboygithub/AqaraGateway/assets/95447044/e1df294a-a6a2-4396-a32b-47416e35f07f)

**Comment by niceboygithub** [comment]
After the firmware 4.0.1 of M1S, it will kill telnet if telnetd is running. Then only solution is flash customized firmware that make telnetd in high priority.
