### ISSUE TITLE
How to get flashable M2 hub

### ISSUE THREAD

**Issue by elylv** [niceboygithub/AqaraGateway#188]
As I understand it, only the Chinese version of the M2 hub is flashable with custom firmware?

How would I go about buying a CN version in the US?  Would ordering from Aliexpress do it?

**Comment by niceboygithub** [comment]
You can buy Chinese version M2 on Aliexpress.

The model of the latest of global M2 was changed and become flashable.

For Global version M2, I may have solution to enable telnet on it. BUT I do not have global version M2 on hand.
