### ISSUE TITLE
G2H 2.2.7_0001.0618 > Is there no method to enable Telnet on this version?

### ISSUE THREAD

**Issue by wehbs** [niceboygithub/AqaraGateway#189]
I tried the hostname sd card file and followed all the instructions including waiting 10+ mins. Sounds like this is probably just not possible on the latest firmware? If that's the case is there any known methods to downgrade the firmware? Any help/guidance is greatly appreciated, thanks!

**Comment by niceboygithub** [comment]
it shall be work in 2.2.7
check your "hostname". Is it UTF-8 encode and "LF" ending

**Comment by peros550** [comment]
I am having the same issue. I created the file in notepad++ checking both the encoding and LF setting. I also tried in version 2.2.5 and then also updated to 2.2.7 , in case 2.2.5 was not a supported version. The SD card seems to be readable by the camera and tried all different filesystems exFAT, FAT32 and NTFS. Any other idea is more than welcome

**Comment by almirus** [comment]
@wehbs @peros550 https://github.com/niceboygithub/AqaraGateway/issues/202#issuecomment-1761807813

**Comment by peros550** [comment]
@almirus unfortunately it didn't work. Any ideas?

**Comment by almirus** [comment]
@peros550 try to connect USB to TTL (PL2303) via usb connector (D+ ->RX, D- ->TX), and check boot log

**Comment by peros550** [comment]
I don't have access to my tools. The problem though is, before I try to open it, that I tried the SD card method to two G2H cameras, one running 2.2.7 and another running 2.2.5 version. I waited for quite a while and telnet didn't work for both of them. I even used directly your file.

**Comment by almirus** [comment]
@peros550 Is the camera definitely European? Not for the Chinese market? Does it work in the Aqara app?

**Comment by peros550** [comment]
I bought these cameras from Aliexpress, probably they were not for European market. The camera works with the aqara app, but probably I have to set mainland china region for them to work. I am not using the aqara app at all, my main use is with homekit. I also have blocked internet access which shouldn't conflict with telnet, yet I also tried having temporarily internet access allowed. 

The SD card hack works only for International version of the camera?

**Comment by peros550** [comment]
Should I pair the camera using the aqara app and try again?

**Comment by peros550** [comment]
So I am glad to inform you that I succesfully enabled telnet on the camera running 2.2.5 firmware. The one running 2.2.7 will have to wait until next weekend. Here are my steps: 
a) Logged in Aqara app. (I had to allow Internet access on my router's access lists)
b) Set any recording function to off. In any case the camera had stopped recording much earlier because of internet being blocked
c) Format the SD using the camera
d) copied the hostname file posted earlier directly to the SD
e) boot the camera with the SD inserted

**Comment by pax0707** [comment]
> So I am glad to inform you that I succesfully enabled telnet on the camera running 2.2.5 firmware. The one running 2.2.7 will have to wait until next weekend. Here are my steps: a) Logged in Aqara app. (I had to allow Internet access on my router's access lists) b) Set any recording function to off. In any case the camera had stopped recording much earlier because of internet being blocked c) Format the SD using the camera d) copied the hostname file posted earlier directly to the SD e) boot the camera with the SD inserted

This did not work for me on 2.2.7.

**Comment by almirus** [comment]
@pax0707 https://github.com/niceboygithub/AqaraGateway/issues/202#issuecomment-1761807813
