### ISSUE TITLE
Aqara hub e1

### ISSUE THREAD

**Issue by rufusgor** [niceboygithub/AqaraGateway#19]
Hello. Opened telnet and installed mosquito, in integration, the connection was successful to the hub. But when trying to read the file /data/zigbee/device. info, an error pops up (2021-06-10 15:41:08 DEBUG gateway 192.168.88.25: Can't get devices: Expecting value: line 1 column 1 (char 0))

"[ro.sys.name]: [Aqara-Hub-E1]
[ro.sys.model]: [lumi.gateway.aqcn02]
[ro.sys.product]: [ZHWG16LM]
[ro.sys.spu]: [AG022]
[ro.sys.sku]: [AG013CNW01]
[ro.sys.ean13]: [6970504211889]
[ro.sys.manufacturer]: [Aqara]
[ro.sys.vendor]: [Lumi United Technology Co., Ltd.]
[ro.sys.fw_ver]: [3.2.4]
[ro.sys.build_num]: [0028]
[ro.sys.mi_fw_ver]: [3.1.3]
[ro.sys.mi_build_num]: [0026]
[ro.sys.hw_ver]: [1.0]
[ro.sys.acc_tags]: [red]
[ro.sys.prop_port]: [55675]
[ro.sys.prop_valid]: [true]
[sys.zb_coordinator]: [/data/zigbee/coordinator.info]
[sys.zb_device]: [/data/zigbee/device.info]
[sys.current_state]: [system_ready]"

**Comment by niceboygithub** [comment]
E1 hub will be supported later.

**Comment by mikeinblue** [comment]
> Hello. Opened telnet and installed mosquito, in integration, the connection was successful to the hub. But when trying to 


 Would you mind tell me the E1 can be connect into mihome?thx

**Comment by niceboygithub** [comment]
> > Hello. Opened telnet and installed mosquito, in integration, the connection was successful to the hub. But when trying to
> 
> Would you mind tell me the E1 can be connect into mihome?thx

Hub E1 support Mi Home and Aqara Home both.

**Comment by rufusgor** [comment]
> > > Hello. Opened telnet and installed mosquito, in integration, the connection was successful to the hub. But when trying to
> 
> > 
> 
> > Would you mind tell me the E1 can be connect into mihome?thx
> 
> 
> 
> Hub E1 support Mi Home and Aqara Home both.

![image](https://user-images.githubusercontent.com/1449265/122878366-5a393b80-d340-11eb-9aba-e4e0b80cb84d.jpeg)

**Comment by rezmus** [comment]
e1 global (aqcn03) at the moment only supports aqara home. it may change with firmware updates later.

**Comment by rufusgor** [comment]
> e1 global (aqcn03) at the moment only supports aqara home. it may change with firmware updates later.

In China's Mi Home region, Aqara Hub E1 is supported

**Comment by rezmus** [comment]
only aqcn02 (e1 cn), my comment was about aqcn03 (e1 global). it does not have mijia integration in current firmware.
