### ISSUE TITLE
Please support M1S(2021) gateway firmware 4.0.3_0012

### ISSUE THREAD

**Issue by CCZU1623** [niceboygithub/AqaraGateway#191]
Home assistant version:2022.10.5
M1S Version:2021
M1S Firmware version:4.0.3_0012
Aqara gateway versios:latest

4.0.3_0012 Firmware supports the secondary gateway of the central gateway，But it won't open Telnet

**Comment by niceboygithub** [comment]
you need to flash custom firmware
