### ISSUE TITLE
M2 2022 ZHWG19LM 好像电路板不同，没有UART

### ISSUE THREAD

**Issue by aemediatodd** [niceboygithub/AqaraGateway#197]
![微信图片_20230917174215](https://github.com/niceboygithub/AqaraGateway/assets/54386158/c31d8282-466c-44e4-8ad3-5f132a48dcf3)
![微信图片_20230917174207](https://github.com/niceboygithub/AqaraGateway/assets/54386158/0a63b0fb-1155-4ba8-a5f7-73a36b00bf11)

**Comment by niceboygithub** [comment]
It has. I lost the picture of M1S
2022.

**Comment by nickgoh** [comment]
> ![微信图片_20230917174215](https://user-images.githubusercontent.com/54386158/268494182-c31d8282-466c-44e4-8ad3-5f132a48dcf3.jpg) ![微信图片_20230917174207](https://user-images.githubusercontent.com/54386158/268494187-0a63b0fb-1155-4ba8-a5f7-73a36b00bf11.jpg)

<img width="504" alt="image" src="https://github.com/niceboygithub/AqaraGateway/assets/5467687/83003a03-8d4f-447c-9e35-b18f94c12da4">

**Comment by aemediatodd** [comment]
thx man ，you R my god
