### ISSUE TITLE
Aqara Hub M1S - Alarm Mode is not synced between HA and Homekit/Mi Home/Aqara Home

### ISSUE THREAD

**Issue by daydy16** [niceboygithub/AqaraGateway#208]
Hey @niceboygithub,

thanks for your great contribution!
Unfortunately the alarm mode state of my m1s hub is not synced between Home Assistant and Homekit/Mi Home/Aqara Home.
When i change the alarm mode in Homekit it is also changed in the Mi Home app/Aqara app but not in Home Assistant.
Same problem when changing the state in Home Assistant. It's not synced to Homekit or Mi home.

<img width="1057" alt="Bildschirmfoto 2023-10-27 um 22 32 17" src="https://github.com/niceboygithub/AqaraGateway/assets/23737896/10c74d22-d372-4efb-b50c-fcb843f85f27">

I'm using the aqara hub m1s, chinese version with your custom firmware: 4.0.6_0006.0646_mi_4.0.4_0006

**Comment by daydy16** [comment]
[547507703360] timed out
16:14:48 – (ERROR) Home Assistant WebSocket API
Updating aqara_gateway alarm_control_panel took longer than the scheduled update interval 0:00:30
16:14:34 – (WARNING) Alarmanlage


Logger: custom_components.aqara_gateway.core.gateway
Source: custom_components/aqara_gateway/core/gateway.py:583
Integration: Aqara Gateway ([documentation](https://github.com/niceboygithub/AqaraGateway), [issues](https://github.com/niceboygithub/AqaraGateway/issues))
First occurred: 15:30:26 (20 occurrences)
Last logged: 16:15:02

Unsupported cmd: {'cmd': 'behave', 'data': {'blue': 0, 'duration': -1, 'green': 0, 'off_period': 200, 'on_period': 100, 'persist': False, 'post_delay': 200, 'pre_delay': 200, 'red': 77, 'repeat': 3}, 'id': 20992, 'type': 'rgb', 'ver': 1}
Unsupported cmd: {'cmd': 'behave', 'data': {'blue': 0, 'duration': -1, 'green': 77, 'off_period': 200, 'on_period': 100, 'persist': False, 'post_delay': 200, 'pre_delay': 200, 'red': 0, 'repeat': 3}, 'id': 33537, 'type': 'rgb', 'ver': 1}
Unsupported cmd: {'cmd': 'behave', 'data': {'blue': 0, 'duration': -1, 'green': 0, 'off_period': 200, 'on_period': 100, 'persist': False, 'post_delay': 200, 'pre_delay': 200, 'red': 77, 'repeat': 3}, 'id': 49664, 'type': 'rgb', 'ver': 1}
Unsupported cmd: {'cmd': 'behave', 'data': {'blue': 0, 'duration': -1, 'green': 0, 'off_period': 200, 'on_period': 100, 'persist': False, 'post_delay': 200, 'pre_delay': 200, 'red': 77, 'repeat': 3}, 'id': 512, 'type': 'rgb', 'ver': 1}
Unsupported cmd: {'cmd': 'behave', 'data': {'blue': 0, 'duration': -1, 'green': 0, 'off_period': 200, 'on_period': 100, 'persist': False, 'post_delay': 200, 'pre_delay': 200, 'red': 77, 'repeat': 3}, 'id': 16896, 'type': 'rgb', 'ver': 1}

**Comment by niceboygithub** [comment]
Won't fix because can't find the way to sync.

**Comment by daydy16** [comment]
Okay, thanks for the update.

I built a workaround with a custom alarm via input_select and some automations.

![IMG_5208](https://github.com/niceboygithub/AqaraGateway/assets/23737896/6ee5eec0-896d-4135-b6fa-08c136ec66ab)
![IMG_5209](https://github.com/niceboygithub/AqaraGateway/assets/23737896/bcd2b54f-6438-4f99-a284-bf75e95cefa0)
