### ISSUE TITLE
Does M2 (global) need an access token?  

### ISSUE THREAD

**Issue by Kaldek** [niceboygithub/AqaraGateway#214]
I have successfully flashed my M2 and have Telnet access, with firmware flashed to 4.0.7_0006.0646.

However I cannot add my M2 to the Aqara Gateway integration in Home Assistant.  It just returns a blank message as below:
![image](https://github.com/niceboygithub/AqaraGateway/assets/26052829/a20b77fd-705f-4196-9df2-81d8b678b008)

Do I need an access token for the M2?  I cannot add the M2 to the Xiamo Smart home app, therefore I cannot use the Xiami Cloud Tokens Extractor.  When I try to add my device into the Xiamo Smart Home app, there is no option for an M2 gateway.

**Comment by Kaldek** [comment]
This is the contents of the /data directory:

```console
# ls -al
drwxrwxr-x    7 1079     1080           488 Nov 29 18:46 .
drwxrwxr-x   13 admin    0              198 Nov 10 18:28 ..
drwxr-xr-x    2 admin    0              232 Nov 29 13:02 ha_driven
drwxrwxr-x    7 1079     1080           776 Jan  1  1970 musics
drwxr-xr-x    4 admin    0              568 Nov 29 22:17 storage
drwxr-xr-x    2 admin    0              320 Jan  1  1970 utils
drw-------    2 admin    0             1480 Nov 29 18:52 zigbee
```

**Comment by niceboygithub** [comment]
M2 do not support Xiaomi Smart Home App.

**Comment by Kaldek** [comment]
OK, so there is no way to integrate the M2 into Home Assistant and control my Aqara Smart Lock A100 then?

**Comment by niceboygithub** [comment]
AqaraGateway supports M2 Global
