### ISSUE TITLE
新出的智能灯带驱动T1好像还是无法识别

### ISSUE THREAD

**Issue by iceskyh** [niceboygithub/AqaraGateway#215]
在aqara home里边添加了，但是在gateway集成里还是看不到

**Comment by iceskyh** [comment]
![1111](https://github.com/niceboygithub/AqaraGateway/assets/130377435/a4ce0c48-0b23-4ad4-9a94-bb95eda87003)
是集成版本有问题？截图是我的集成版本，是直接点击readme文档里的链接安装的

**Comment by niceboygithub** [comment]
You need to use redownload on master branch.

**Comment by iceskyh** [comment]
重新下载后可以在集成里看到设备了，但只能控制开关，无法获取和控制设备的实际亮度
