### ISSUE TITLE
m2怎么刷不上？

### ISSUE THREAD

**Issue by xjy65226500** [niceboygithub/AqaraGateway#216]
我是按下图接引脚的，usb转ttl是ch340模块。
最后是这种效果，是因为我没接3.3v吗？m2我是通电了的
固件是用的root 3.5.3  
![屏幕截图 2023-12-07 050631](https://github.com/niceboygithub/AqaraGateway/assets/136147699/8356b868-169c-4053-bed0-96aecf7d73c6)
<img width="504" alt="271871029-83003a03-8d4f-447c-9e35-b18f94c12da4" src="https://github.com/niceboygithub/AqaraGateway/assets/136147699/fabcbd98-a864-4dad-bece-bd25d833e1c5">

**Comment by niceboygithub** [comment]
You can't use AqaraGatway.exe on M2 PoE version.
Use Gateway Global tool.

**Comment by leeaash** [comment]
> You can't use AqaraGatway.exe on M2 PoE version. Use Gateway Global tool.
If use Gateway Global, which item would be chosen in ttl, and which one modified firmware should be used? Dose the ttl should be mofiied for M2 PoE version?
