### ISSUE TITLE
 will support c3 automatic curtain?

### ISSUE THREAD

**Issue by aemediatodd** [niceboygithub/AqaraGateway#217]
![Screenshot_2023-12-17-04-29-25-726_com lumiunited aqarahome](https://github.com/niceboygithub/AqaraGateway/assets/54386158/15dae2bb-80a6-4d03-ac98-e33dce9a9de4)

**Comment by niceboygithub** [comment]
Need the model number to support.

**Comment by niceboygithub** [comment]
Please use the master branch for test.
