### ISSUE TITLE
M1S always turn on a yellow light, and i cannot reset my M1s.

### ISSUE THREAD

**Issue by xiaoyuervae** [niceboygithub/AqaraGateway#22]
After flush the "Not Flash Custom firmware method", then i execute the reboot cmd, unfortunately, my M1s cannot connect to my Mi home devices or homekit.
And i cannot reset it using press the button...
Is there any ways to help me reset this?

**Comment by niceboygithub** [comment]
Need Uart log to identify the question.

The possible cause is that your post_init.sh is incorrect.

**Comment by cnwangfeng** [comment]
@xiaoyuervae , may you try press the button 10 times? It would reset to Factory Default.
