### ISSUE TITLE
G2H Mosquitto Glibc error

### ISSUE THREAD

**Issue by Silverow** [niceboygithub/AqaraGateway#221]
> > Try to telnet to G2H. and use the following command to have a try.
> > ```
> > killall -9 mosquitto; /data/bin/mosquitto -d
> > ```
> 
> i get
> 
> > /data/bin/mosquitto: /lib/libm.so.6: version GLIBC_2.29 not found (required by /data/bin/mosquitto)
> > /data/bin/mosquitto: /lib/libc.so.6: version GLIBC_2.25 not found (required by /data/bin/mosquitto)
> > /data/bin/mosquitto: /lib/libc.so.6: version GLIBC_2.28 not found (required by /data/bin/mosquitto)

I got the same result. What can be done about it?

_Originally posted by @Silverow in https://github.com/niceboygithub/AqaraGateway/issues/171#issuecomment-1871751144_

**Comment by niceboygithub** [comment]
You use wrong mosquitto. Where did you get it?

**Comment by Silverow** [comment]
I telneted in and ran these commands from manual

> mkdir /data/bin
cd /data/bin
wget -O /tmp/curl "http://master.dl.sourceforge.net/project/aqarahub/binutils/curl?viasf=1"; chmod +x /tmp/curl
/tmp/curl -s -k -L -o /data/bin/mosquitto https://raw.githubusercontent.com/niceboygithub/AqaraCameraHubfw/main/binutils/mosquitto; chmod a+x /data/bin/mosquitto

**Comment by niceboygithub** [comment]
Can you use this command 'agetprop | grow miio' and paste the output here?

**Comment by Silverow** [comment]
> Camera-Hub-G2H` login: root                                    
BusyBox v1.24.1 (2020-04-28 18:44:59 CST) built-in shell (ash)
Enter 'help' for a list of built-in commands.                 
Welcome to Linux.                                             
#agetprop | grep miio                                        
#

Empty. I looked through the full output of the agetprop command, nothing like "miio".

**Comment by niceboygithub** [comment]
I tested the commands in my G2H and without any problems to run mosquitto.

can you get the boot log and the output of agetprop?

**Comment by Silverow** [comment]
> I telneted in and ran these commands from manual
> 
> > mkdir /data/bin
> > cd /data/bin
> > wget -O /tmp/curl "http://master.dl.sourceforge.net/project/aqarahub/binutils/curl?viasf=1"; chmod +x /tmp/curl
> > /tmp/curl -s -k -L -o /data/bin/mosquitto https://raw.githubusercontent.com/niceboygithub/AqaraCameraHubfw/main/binutils/mosquitto; chmod a+x /data/bin/mosquitto

Repeat commands and it works. Thanks
