### ISSUE TITLE
Aqara G2H camera motion sensor

### ISSUE THREAD

**Issue by NikDevx** [niceboygithub/AqaraGateway#23]
Hello
Thanks for your work!

Is it possible to add motion sensor from Aqara G2H camera to Home Assistant?

**Comment by niceboygithub** [comment]
Sorry, I did not find the solution to add montion sensor from Aqara Camera  G2H.

**Comment by NikDevx** [comment]
> Sorry, I did not find the solution to add montion sensor from Aqara Camera G2H.

I understood.
Thanks

**Comment by almirus** [comment]
Aqara G2H camera is support motion sensor via HomeKit 
![image](https://github.com/niceboygithub/AqaraGateway/assets/16898685/7012fac0-4fab-473d-b36e-912c8372a4a9)
