### ISSUE TITLE
Please help find out UART pins for Aqara M1S 2022

### ISSUE THREAD

**Issue by Kunjinkao0** [niceboygithub/AqaraGateway#233]
Hi there, I have a Aqara M1s 2022 version of my gateway, I want to downgrade its firmware but when I pry it out, I see there is no indicators to show which pin is RX/TX and GRD, I'm not familiar with how these hardware works, can somebody tell me if you had some experience on which pins are the correct ones? Really appreciate your help!

Front: 
![front](https://github.com/niceboygithub/AqaraGateway/assets/3669403/36420c44-bb26-4adc-9c6c-048422661f45)

Back:
![back](https://github.com/niceboygithub/AqaraGateway/assets/3669403/892da7a4-4582-4610-9ecd-0552d4c7be13)

**Comment by niceboygithub** [comment]
I forgot the exact the pins but it is easy to find out.

![image](https://github.com/niceboygithub/AqaraGateway/assets/74046071/143e553d-aab4-4d62-a599-0fc1e6310c64)

These are the three pins. You can find out the ground first.
Use multi-meter to find the ground pin. Then the other two pins are tx and rx pins.

**Comment by Kunjinkao0** [comment]
@niceboygithub great thanks! And i may still need one more help on this, do you know where can i support its 3.3V volt power? in which pin maybe? i just can't plug it into 220V directly which is really scared 😢

**Comment by Kunjinkao0** [comment]
Appreciate your response! Thank you! @niceboygithub

**Comment by mcmichaelchan** [comment]
@Kunjinkao0 Have you successfully found the pins?
