### ISSUE TITLE
The Aqara integration cannot restore connection after Aqara Hub M2 restart

### ISSUE THREAD

**Issue by Shura1oplot** [niceboygithub/AqaraGateway#237]
The HA Aqara integration cannot read buttons events and sensor data after Aqara Hub M2 restart. The connection is restored after the integration reload.

Steps to reproduce:
1. Check buttons or sensors - should work
2. Restart an Aqara Hub M2 (using telnet or disconnect from power supply)
3. Wait a couple of minutes
4. Check buttons or sensors - no events populated
5. Reload Aqara integration
6. Check buttons or sensors - should work

HA: 2024.3.0
AqaraGateway: 0.2.2
Aqara Hub M2: 4.1.0_0003.0650 (modified, from https://github.com/niceboygithub/AqaraM1SM2fw)

**Comment by niceboygithub** [comment]
Please try to test 0.2.4
