### ISSUE TITLE
HA core 2024.3 is not compatible with aqara integration

### ISSUE THREAD

**Issue by bytebility** [niceboygithub/AqaraGateway#239]
Dears, HA core 2024.3 is not compatible with aqara integration. When I upgraded to core 2024.3.0, more than 60 devices in the aqara integration were displayed as unavailable. After restoring to core 2024.2.5, everything was normal. It should be that the API and functional interfaces of core 2024.3 have changed.

**Comment by lihuohuo9527** [comment]
I don't think it's a problem with HA core, but with Supervison.

**Comment by niceboygithub** [comment]
Please try to use 0.2.4 release

**Comment by bytebility** [comment]
> Please try to use 0.2.4 release

It works! 0.2.4 had fixed it. Thank you very much!

**Comment by bytebility** [comment]
It works! 0.2.4 had fixed it. Thank you very much!

**Comment by bytebility** [comment]
> Please try to use 0.2.4 release

It works! 0.2.4 had fixed it. Thank you very much!
