### ISSUE TITLE
I restart HA but Ican't find it in the integration.

### ISSUE THREAD

**Issue by percy10442** [niceboygithub/AqaraGateway#24]
<img width="597" alt="截圖 2021-06-27 上午10 40 40" src="https://user-images.githubusercontent.com/78840128/123531114-67856a00-d734-11eb-804f-74a331dccaa6.png">
<img width="473" alt="截圖 2021-06-27 上午10 40 25" src="https://user-images.githubusercontent.com/78840128/123531117-6b18f100-d734-11eb-87be-447772cb756c.png">
<img width="1488" alt="截圖 2021-06-27 上午10 41 15" src="https://user-images.githubusercontent.com/78840128/123531118-6bb18780-d734-11eb-9884-2f27c837a0b4.png">

**Comment by percy10442** [comment]
I can add it in the HACS, so I clode this issue.

**Comment by percy10442** [comment]
I add it by HACS, but I still can't find it in the integration.

**Comment by niceboygithub** [comment]
did you try refresh in browser or clear the cache of browser?

**Comment by percy10442** [comment]
You are right. I delete cookies and refresh in browser and refresh and I find it in the integration. Thank you.
