### ISSUE TITLE
Aqara Gateway integration occurs errors when update to Version 0.2.3

### ISSUE THREAD

**Issue by 645340633** [niceboygithub/AqaraGateway#240]
When I update the integration to  Version 0.2.3 release , it occurs error that cannot be loaded. And my HA core is 2024.3.1, When rollback to 0.2 2, the errors disappear
![Screenshot_20240316_082858](https://github.com/niceboygithub/AqaraGateway/assets/80463778/de72cd09-a58f-4d24-9b22-5d3de23ec781)

**Comment by niceboygithub** [comment]
Please try restart M2 then restart HA.

**Comment by 645340633** [comment]
I have tried， But it didn't work.

**Comment by 645340633** [comment]
Version 0.2.3, it still doesn't work.

**Comment by nevotens** [comment]
Same for me. Tried several times.

**Comment by niceboygithub** [comment]
please have a try on master branch

**Comment by niceboygithub** [comment]
Please try to use 0.2.4 release

**Comment by 645340633** [comment]
> Please try to use 0.2.4 release

yes. it work
