### ISSUE TITLE
Steps of integrating Aqara M1S gen1 CN

### ISSUE THREAD

**Issue by vit5041** [niceboygithub/AqaraGateway#247]
Hi!
can you please help. 

I have this hub:

Model: lumi.gateway.acn01
Hardware version: Linux
Firmware version: 4.0.4_0006

(Added in Mi Home, telnet closed).

How to add it to AqaraGateway?

**Comment by niceboygithub** [comment]
You need to wired UART to clean telnet password first.
Another solution is that change to use hub E1. It is easier.

**Comment by vit5041** [comment]
OK, thank you.
I managed and steps on highlevel are:


1. use gw_global_tool to clear admin password (on this step I did not flash modified firmware although it was offered, but for M2)
2. open telnet through clicks. 

in this condition I managed to integrate Gateway to HA but nothing was working there. So I come to conclusion that customized firmware is a must.

I powered off GW and in the next power on magic clicks  didn't work anymore, I tried many times and reset GW. It switched to Aqara Home mode, I had to switch it to Mijia again, added to Mi Home, all previosly added devices were lost.

3. Magic clicks worked again, I opened telnet and update firmware using  "Flash M1S modified firmware method"

After that both Mi Home and Home Assistant work like charm.

So the key point — modified formware is a must and better to make it on first steps, through gw_global_tool or after, from telnet cli.

Hopefully it may be helpful.

**Comment by vit5041** [comment]
issue closed

**Comment by kai-zer-ru** [comment]
https://github.com/niceboygithub/AqaraGateway/issues/246 look here

**Comment by maodun96** [comment]
> 好的谢谢。 我管理的高级步骤是：
> 
> 1. 使用 gw_global_tool 清除管理员密码（在这一步中，我没有刷新修改后的固件，尽管提供了它，但对于 M2）
> 2. 通过点击打开telnet。
> 
> 在这种情况下，我设法将网关集成到 HA，但那里没有任何作用。所以我得出的结论是定制固件是必须的。
> 
> 我关闭了 GW 电源，下次开机时魔法点击不再起作用，我尝试了很多次并重置了 GW。切换到Aqara Home模式，我只好再次切换到米家，添加到米家，之前添加的设备全都丢失了。
> 
> 3. 魔法点击再次起作用，我打开telnet并使用“Flash M1S修改固件方法”更新固件
> 
> 之后，米家和家庭助理就都发挥了魅力。
> 
> 因此，关键点 - 修改后的固件是必须的，并且最好在第一步中通过 gw_global_tool 或之后从 telnet cli 进行修改。
> 
> 希望它可能有所帮助。

Is gw_global_tool used through a TTL connection?

**Comment by vit5041** [comment]
> > 好的谢谢。 我管理的高级步骤是：
> > 
> > 1. 使用 gw_global_tool 清除管理员密码（在这一步中，我没有刷新修改后的固件，尽管提供了它，但对于 M2）
> > 2. 通过点击打开telnet。
> > 
> > 在这种情况下，我设法将网关集成到 HA，但那里没有任何作用。所以我得出的结论是定制固件是必须的。
> > 我关闭了 GW 电源，下次开机时魔法点击不再起作用，我尝试了很多次并重置了 GW。切换到Aqara Home模式，我只好再次切换到米家，添加到米家，之前添加的设备全都丢失了。
> > 
> > 3. 魔法点击再次起作用，我打开telnet并使用“Flash M1S修改固件方法”更新固件
> > 
> > 之后，米家和家庭助理就都发挥了魅力。
> > 因此，关键点 - 修改后的固件是必须的，并且最好在第一步中通过 gw_global_tool 或之后从 telnet cli 进行修改。
> > 希望它可能有所帮助。
> 
> Is gw_global_tool used through a TTL connection?

Right, it works over TTL and Terra Term app.

**Comment by maodun96** [comment]
Thank you, I have also successfully carried out the operation in the same way as you.

@vit5041
