### ISSUE TITLE
How to listen for the button click event of the T1 switch?

### ISSUE THREAD

**Issue by mcmichaelchan** [niceboygithub/AqaraGateway#251]
I have added the T1 switch to my M1S gateway, but I only found the power status and a switch sensor. How can I listen for the button click event and tell which button is clicked in HA?
<img width="1143" alt="image" src="https://github.com/niceboygithub/AqaraGateway/assets/15685780/5bf65079-104a-4792-b441-39b5251cb82a">
<img width="1067" alt="image" src="https://github.com/niceboygithub/AqaraGateway/assets/15685780/afe46932-66a8-44f4-957b-fc3fd5f95dbc">

**Comment by CharmingCheung** [comment]
You should first learn about the relationship between Devices and Entities in HA. The click state of your Aqara T1 is an entity provided by this device. So, you should be listening to the Entity, not Device.

Such as:
![image](https://github.com/niceboygithub/AqaraGateway/assets/16662340/4c40178a-b03a-4420-91f3-401eb2d7da11)

**Comment by mcmichaelchan** [comment]
> You should first learn about the relationship between Devices and Entities in HA. The click state of your Aqara T1 is an entity provided by this device. So, you should be listening to the Entity, not Device.
> 
> Such as: ![image](https://private-user-images.githubusercontent.com/16662340/322338939-4c40178a-b03a-4420-91f3-401eb2d7da11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTE1MzksIm5iZiI6MTcxMzE1MTIzOSwicGF0aCI6Ii8xNjY2MjM0MC8zMjIzMzg5MzktNGM0MDE3OGEtYjAzYS00NDIwLTkxZjMtNDAxZWIyZDdkYTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDAzMjAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZDBlZjJjMzg0NjYxY2E4OTRlMTZmYzlmOGFkY2NmMDM2YjVlMDUyMjdlZWNiZGU4ZDg0YzcyNTg2YmUzNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jlHryTSuRq6CC_J2EhnJ6imhrSsXuIqUly38f2eoUFg)

Thank you🥰
