### ISSUE TITLE
M1S hub can't enter arm_night mode.

### ISSUE THREAD

**Issue by percy10442** [niceboygithub/AqaraGateway#26]
After updating the latest version, the M1S hub cannot enter arm_night mode.But the previous version is normal.

**Comment by niceboygithub** [comment]
Yes, it is supported.
You can use service call to enter night alarm mode.
"Alarm control panel: Arm night"

**Comment by percy10442** [comment]
https://user-images.githubusercontent.com/78840128/124378203-c756b480-dce2-11eb-9049-022ab75f543b.mov


https://user-images.githubusercontent.com/78840128/124378242-01c05180-dce3-11eb-9360-b4f14043f87b.mov

I tried to put it into night alarm mode, but it will be disarm immediately.

**Comment by niceboygithub** [comment]
OK, fixed.

**Comment by percy10442** [comment]
> OK, fixed.

Otherwise, I can’t control switch in 0.0.3. It’s always off.

**Comment by niceboygithub** [comment]
Which switch ?

Aqara home or mi home mode?

**Comment by percy10442** [comment]
I set it in Mi home mode. Switch is Aqara E1 and D1.But it’s normal in 0.0.2.

**Comment by niceboygithub** [comment]
I did not modify the code related to E1 switch. So it shall be work.
Can you send the logs of both switch while the actions in Mi Home app. Thanks,
