### ISSUE TITLE
The Climent AC Controller cannot be found on AqaraGateway for P3

### ISSUE THREAD

**Issue by cnwangfeng** [niceboygithub/AqaraGateway#27]
Hi, 

After I enable the telnet function to the P3, I can successfully configure the Aqara P3 gateway to the Homeassistaant. However, there are only ALARM and TH Sensor that could be found. No climate.ac_controller can be setup. 

As I know, The device type of P3 is heater-cooler, which can't be supported by the original thermostat climate device in the previous Homeassistant.

**Comment by niceboygithub** [comment]
As README said. 

**Control Zigbee devices from Home Assistant with Aqara Gateway**

This plugin is support the zigbee function of Aqara Gateway.

**Comment by cnwangfeng** [comment]
Yes. Sorry for the message left. I think you are right. 

Hope it can be supported in the future. Thanks again for your great work.
