### ISSUE TITLE
Aqara Hub E1 doesn't show any devices and entities

### ISSUE THREAD

**Issue by EricCorleone** [niceboygithub/AqaraGateway#273]
I've done everything, including switching to Mi Home mode, enabling telnet, flashing the modified firmware, then swtiching back to Aqara Home mode and connecting it to the Aqara Home app. After that, the Aqara Gateway integration did show up in the integration list, but after configured there were no entities at all. Even though I had connected my curtain and some switches to it, there were still no entities.
![image](https://github.com/niceboygithub/AqaraGateway/assets/55615178/540ffddf-57b3-4893-aa2d-1b23bf3e9f5a)
The Chinese characters in the screenshot says "No devices or entities".
I think even if there's no device connected to the hub, the hub itself should show up as a device, right?

**Comment by niceboygithub** [comment]
Please upgrade the version of HA and AqaraGateway

**Comment by EricCorleone** [comment]
Sorry, my bad, I didn't notice the version lol. Can't believe it's that old. After I upgraded the integration to the latest version, it works fine now. Maybe it's because the integration was not installed from HACS at first, so it never got upgraded before.
