### ISSUE TITLE
是否可以让瞬时事件触发后立刻重置为None

### ISSUE THREAD

**Issue by EricCorleone** [niceboygithub/AqaraGateway#275]
举个例子，智能开关的按键事件（比如button_1_single、button_3_double）理应是瞬时事件，每次触发后应该立刻重置为None更合理，而不是一直持续留在那里。之所以提出这个，是因为我会将智能开关转为无线开关，然后通过按键事件来切换其他非Aqara品牌的灯具的开和关。但是如果瞬时事件一直停留的话，每次通过某个按键事件（例如button_2_double）开启某个灯具之后，我就无法再将其关闭，必须先触发其他按键事件之后才能再次触发（button_2_double）来将该灯具关闭，非常不方便。
麻烦大佬考虑一下是否可以改进一下，包括但不限于智能开关的事件，其他设备的瞬时事件例如门锁事件等等如果可以一起改就更好了，谢谢！
![IMG_7099](https://github.com/niceboygithub/AqaraGateway/assets/55615178/7dd1e9b1-d7b3-4793-b7eb-e79703996644)

**Comment by EricCorleone** [comment]
看了一下你的代码，似乎是写了每次按键后重置的逻辑，但是并没有生效，我直接改了：
![image](https://github.com/niceboygithub/AqaraGateway/assets/55615178/1cc3415e-68ad-476a-a4dd-d0978daf90a5)
你看是你自己改，还是我给你提PR？

**Comment by lixaster** [comment]
确实，2024.6之前都是正常的。升级到2024.7之后就不能重置开关状态了。

**Comment by lixaster** [comment]
确实是的，升级到2024.7就不能重置为空状态了。

**Comment by bugensui2022** [comment]
最新版的ha，确实有这个问题

**Comment by EricCorleone** [comment]
原来是更新了2024.7才会这样吗，我最近才第一次用这个集成，还以为一直都有这个问题

**Comment by G0m3e** [comment]
多谢大佬提交的代码，现在用Aqara转无线开关控制其他非Aqara的灯很丝滑。在升级2024.7之前，好像Aqara转无线也有时候不灵敏，现在延迟基本没有了
