### ISSUE TITLE
Can't add HUB M1S

### ISSUE THREAD

**Issue by mifrith** [niceboygithub/AqaraGateway#29]
Installed via HACS. I did everything according to the instructions. Without flashing the hub and with it. When I try to add an integration, I enter ip, password and token. The indicator is spinning, then the inscription "Canceled" and nothing happens. The logs are also empty.

**Comment by niceboygithub** [comment]
Did you change password?
If you did not change the password in telnet, please do not input the password.

**Comment by mifrith** [comment]
Tried without password and with password. The result is the same.

> Did you change password?
> If you did not change the password in telnet, please do not input the password.

Tried without password and with password. The result is the same.

**Comment by niceboygithub** [comment]
1. Make sure your M1S is in Mi Home mode.
2. Get the token
3. Use way 2 or way 3 in https://gist.github.com/zvldz/1bd6b21539f84339c218f9427e022709
4. After enable telnet, use putty to login telnet

**Comment by mifrith** [comment]
1. M1S is in Mi Home mode
2. Token received
3. Hub telnet is on
4. Putty connection via telnet goes smoothly
Doesn't connect, the same message "Canceled"

**Comment by mifrith** [comment]
Maybe there is a way to log all actions during connection?

**Comment by niceboygithub** [comment]
What is your result in your step 4?

Can you make sure that your HA and M1S are in same domain (like 192.168.1.x)?

**Comment by mifrith** [comment]
I log in to the hub via putty with the admin and without a password. Yes HA and hub are in the same domain.

**Comment by niceboygithub** [comment]
Can you input the following command in putty then get the results?

```
getprop ro.sys.model
```

**Comment by mifrith** [comment]
Yes, of course, here's the output: lumi.gateway.aeu01

**Comment by niceboygithub** [comment]
Not test eu version before.
If you can help to test, it will be great!

https://github.com/niceboygithub/AqaraGateway/blob/2261ec8316aec7af4155127cf052d1955a99cf31/custom_components/aqara_gateway/core/utils.py#L31

change the model to aeu01

**Comment by mifrith** [comment]
It helped, connected the first time.

**Comment by niceboygithub** [comment]
As README, this plugin is supported M1S CN now.
If you can verify on M1S EU, I can add it to support list.

**Comment by mifrith** [comment]
OK, I can help with these.

**Comment by niceboygithub** [comment]
Use M1S EU in Mi home mode.
Add your zigbee devices and see them if work as normal

**Comment by chaplyk** [comment]
I have uncommented line 35 `'lumi.gateway.aeu01': ["Aqara", "Gateway M1S", "HM1S-G01"],` and installed integration.
HA works OK with my Aqara sensors added in Mi Home. 

However, I have a Aqara N100 lock which cannot be added in Mi Home (Zigbee version supports Aqara Home app only). Since there is no custom firmware for EU version in your repo, can you suggest how I can switch from Mi Home mode to Aqara? (I believe that if I do reset on device - token will change, right?)

**Comment by niceboygithub** [comment]
> I have uncommented line 35 `'lumi.gateway.aeu01': ["Aqara", "Gateway M1S", "HM1S-G01"],` and installed integration.
> HA works OK with my Aqara sensors added in Mi Home.
> 
> However, I have a Aqara N100 lock which cannot be added in Mi Home (Zigbee version supports Aqara Home app only). Since there is no custom firmware for EU version in your repo, can you suggest how I can switch from Mi Home mode to Aqara? (soft reset on device disables telnetd)


I have a idea. but I did not verity it yet. You can have a try
While M1S switch to Aqara Home, M1S do not do reboot. So there is a chance to write "post_init.sh". With "post_init.sh", it can enable telnet.

1. telnet to M1S
2. run script like the following code
```
#!/bin/sh

CUSTOM_POST_INIT=/data/scripts/post_init.sh
watching_post_init() {
    if [ ! -x ${CUSTOM_POST_INIT} ]; then
        mkdir -p /data/scripts/
        echo -e '#!/bin/sh\r\n\r\nfw_manager.sh -r\r\necho enable > /sys/class/tty/tty/enable\r\ntelnetd' > ${CUSTOM_POST_INIT}
        chmod a+x ${CUSTOM_POST_INIT}
    fi
}


main() {
    while [ 1 ]; do sleep 1; watching_post_init; done
}

main

```
3. switch to Aqara Home mode (press 10 times of button and 2 times of button)

**Comment by chaplyk** [comment]
You are a magician.

I have launched the code above (sent main() to background) and reset the hub to Aqara mode.
After reset all data was gone but telnet remained opened (even old session remained online).
I have then recreated post_init.sh and installed mosquito using a snippet from README.md.

The only problem is that /data/miio folder is now gone which contained the file with the token. However, somehow integration automatically discovered the hub and added it without token.
I have verified that sensors work in HA as expected.

**Comment by niceboygithub** [comment]
> You are a magician.
> 
> I have launched the code above (sent main() to background) and reset the hub to Aqara mode.
> After reset all data was gone but telnet remained opened (even old session remained online).
> I have then recreated post_init.sh and installed mosquito using a snippet from README.md.
> 
> The only problem is that /data/miio folder is now gone which contained the file with the token. However, somehow integration automatically discovered the hub and added it without token.
> I have verified that sensors work in HA as expected.


miio token is useless in Aqara home mode. You can ignore it in Aqara Home mode.

It is great that this component is helped to you.

**Comment by shift-del1** [comment]
I would like to test the solution with M1S EU, but have no experience with Linux. Can any of you please create something similar on the readme page for manual telnet etc. I can copy into telnet and run? My goal would be:
1. put M1S EU into Mi Home mode
2. add it to the integration to gain access to telnet
3. run specific commands to retain telnet (this is where I need your help)
4. switch to Aqara Home mode
5. have Aqara Home and Home Assistant access parallel
Thank you.

**Comment by chaplyk** [comment]
@shift-del1 once EU hub is added to your Mi account:

Obtain info about gateway:
`bash <(curl -L https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/raw/master/run.sh)`

Enable telnet:
`pip3 install python-miio`
`miiocli device --ip <gateway_id> --token <gateway_token> raw_command set_ip_info '{"ssid":"\"\"","pswd":"123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd"}'`
_Replace <gateway_ip> and <gateway_token> with info received from the first command. Nothing else has to be changed._

Telnet to hub using username _admin_:
`telnet <gateway_ip>`

Create a script with any name (f.e. enable_telnet.sh) and paste the following code (can use _vi_ to create script):
```
#!/bin/sh

CUSTOM_POST_INIT=/data/scripts/post_init.sh
watching_post_init() {
    if [ ! -x ${CUSTOM_POST_INIT} ]; then
        mkdir -p /data/scripts/
        echo -e '#!/bin/sh\r\n\r\nfw_manager.sh -r\r\necho enable > /sys/class/tty/tty/enable\r\ntelnetd' > ${CUSTOM_POST_INIT}
        chmod a+x ${CUSTOM_POST_INIT}
    fi
}


main() {
    while [ 1 ]; do sleep 1; watching_post_init; done
}

main
```
Then run the script:
`sh enable_telnet.sh`

With a script running switch hub to Aqara mode (press 10 + 2 times on hub) and add it to Aqara Home app.
Telnet connection should remain active. Stop the script with Ctrl+C.

Perform steps from readme to enable integration:
```mkdir /data/bin
cd /data/bin
wget -O /data/bin/curl "http://master.dl.sourceforge.net/project/mgl03/bin/curl?viasf=1"
chmod +x /data/bin/curl
/data/bin/curl -s -k -L -o /data/bin/mosquitto https://raw.githubusercontent.com/niceboygithub/AqaraM1SM2fw/main/binutils/mosquitto
chmod a+x /data/bin/mosquitto

mkdir /data/scripts
cd /data/scripts
/data/bin/curl -s -k -L -o /data/scripts/post_init.sh https://raw.githubusercontent.com/niceboygithub/AqaraM1SM2fw/main/binutils/post_init.sh
chmod +x /data/scripts/post_init.sh

reboot
```

**Comment by shift-del1** [comment]
Thank you chaplyk, I really appreciate your detailed description. Currently I'm away from the hub, but once I get home, I will give it a try. Some part was already done (like token retrieval and telnet enabled), but your instructions are vital for the complete success 😊

**Comment by shift-del1** [comment]
Hello chaplyk,

Everything went fine until the last step, where I should have enable the integration (so telnet was runing after switched to Aqara home app). I copied the script with the embedded button in the top right corner and pasted in the telnet window, device rebooted and not able to start up anymore. Any idea what could go wrong (I guess the post_init.sh) and how to fix it? No action after holding the button for 10s or pressing it 10 times. Thanks in advance.

**Comment by binakot** [comment]
The same situation.

I just bought `Aqara Hub M1S EU` / `HM1S-G01` / `lumi.gateway.aeu01`.

On the first run I switched from `Aqara Home` app to `MiHome` app via 10-times button press for reset and 2-times press after reset to switch in `MiHome` mode.
After I connect hub to `MiHome` patched by `Vevs` in region `China Mainland`.
And I update firmware to the latest `3.1.5_0020`.
Everything works like a charm.

Than I collect `device token` by next commands (values are faked):

```bash
$ bash <(curl -L https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/raw/master/run.sh)

NAME: Aqara Hub M1S
ID: 123456
IP: 192.168.0.123
TOKEN: qwe123
MODEL: lumi.gateway.aeu01
```

After I enable `telnet` with commands:

```bash
$ sudo pip3 install python-miio 
$ miiocli device --ip 192.168.0.123 --token qwe123 raw_command set_ip_info '{"ssid":"\"\"","pswd":"123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd"}'
$ telnet 192.168.0.123 
> login: admin

Aqara-Hub-M1S-9512 login: admin
RLX Linux version 3.0
         _           _  _
        | |         | ||_|                 
   _  _ | | _  _    | | _ ____  _   _  _  _ 
  | |/ || |\ \/ /   | || |  _ \| | | |\ \/ /
  | |_/ | |/    \   | || | | | | |_| |/    \
  |_|   |_|\_/\_/   |_||_|_| |_|\____|\_/\_/

For further information check:
http://processor.realtek.com/


BusyBox v1.22.1 (2021-09-01 19:43:53 CST) built-in shell (ash)
Enter 'help' for a list of built-in commands.
#
```

I tried `Flash M1S Custom firmware method` but it is not supported for `EU` hubs:

```bash
$ cd /tmp && wget -O /tmp/curl "http://master.dl.sourceforge.net/project/mgl03/bin/curl?viasf=1" && chmod a+x /tmp/curl
/tmp/curl -s -k -L -o /tmp/m1s_update.sh 
$ https://raw.githubusercontent.com/niceboygithub/AqaraM1SM2fw/main/modified/M1S/m1s_update.sh
$ chmod a+x /tmp/m1s_update.sh && /tmp/m1s_update.sh
m1s_update.sh revision: 2
type: lumi.gateway.aeu01, model: AH_M1S
This is not supported M1S and exit!
```

Via `telnet` I applied `Not Flash Custom firmware method`:

```bash
$ mkdir /data/bin
$ cd /data/bin
$ wget -O /data/bin/curl "http://master.dl.sourceforge.net/project/mgl03/bin/curl?viasf=1"
$ chmod +x /data/bin/curl
$ /data/bin/curl -s -k -L -o /data/bin/mosquitto 
$ https://raw.githubusercontent.com/niceboygithub/AqaraM1SM2fw/main/binutils/mosquitto
$ chmod a+x /data/bin/mosquitto

$ mkdir /data/scripts
$ cd /data/scripts
$ /data/bin/curl -s -k -L -o /data/scripts/post_init.sh 
$ https://raw.githubusercontent.com/niceboygithub/AqaraM1SM2fw/main/binutils/post_init.sh
$ chmod +x /data/scripts/post_init.sh

$ reboot
```

After reboot `MiHome` works with `Aqara Hub M1S` and device is still available via `telnet`.

But I got `Aborted` message in `Home Assistant` on every try to integrate `Aqara Hub`...

![image](https://user-images.githubusercontent.com/1783893/140802522-3aab0b3a-2149-4d7b-997a-61e070e04815.png)

![image](https://user-images.githubusercontent.com/1783893/140802603-a98088d8-647d-44ee-b21f-81f238a9cbda.png)

**Comment by binakot** [comment]
Trying to uncomment row like here: https://github.com/niceboygithub/AqaraGateway/issues/29#issuecomment-889136414

```python
'lumi.gateway.aeu01': ["Aqara", "Gateway M1S", "HM1S-G01"],
```

**Comment by binakot** [comment]
And it works ;)

![image](https://user-images.githubusercontent.com/1783893/140804424-0b84c3f7-2288-4e3c-be62-b8a5a1ed8b28.png)

**Comment by kizimenko** [comment]
> You are a magician.
> 
> I have launched the code above (sent main() to background) and reset the hub to Aqara mode. After reset all data was gone but telnet remained opened (even old session remained online). I have then recreated post_init.sh and installed mosquito using a snippet from README.md.
> 
> The only problem is that /data/miio folder is now gone which contained the file with the token. However, somehow integration automatically discovered the hub and added it without token. I have verified that sensors work in HA as expected.

What you have in HA from zigbee n100? can u add some pictures?

**Comment by lonsdaleite** [comment]
I can also commit that lumi.gateway.aeu01 works without any issues after modifying utils.py in 3 rows.

**Comment by sorryusernameisalreadytaken** [comment]
> > I have uncommented line 35 `'lumi.gateway.aeu01': ["Aqara", "Gateway M1S", "HM1S-G01"],` and installed integration.
> > HA works OK with my Aqara sensors added in Mi Home.
> > However, I have a Aqara N100 lock which cannot be added in Mi Home (Zigbee version supports Aqara Home app only). Since there is no custom firmware for EU version in your repo, can you suggest how I can switch from Mi Home mode to Aqara? (soft reset on device disables telnetd)
> 
> I have an idea. but I did not verity it yet. You can have a try While M1S switch to Aqara Home, M1S do not do reboot. So there is a chance to write "post_init.sh". With "post_init.sh", it can enable telnet.
> 
> 1. telnet to M1S
> 2. run script like the following code
> 
> ```
> #!/bin/sh
> 
> CUSTOM_POST_INIT=/data/scripts/post_init.sh
> watching_post_init() {
>     if [ ! -x ${CUSTOM_POST_INIT} ]; then
>         mkdir -p /data/scripts/
>         echo -e '#!/bin/sh\r\n\r\nfw_manager.sh -r\r\necho enable > /sys/class/tty/tty/enable\r\ntelnetd' > ${CUSTOM_POST_INIT}
>         chmod a+x ${CUSTOM_POST_INIT}
>     fi
> }
> 
> 
> main() {
>     while [ 1 ]; do sleep 1; watching_post_init; done
> }
> 
> main
> ```
> 
> 3. switch to Aqara Home mode (press 10 times of button and 2 times of button)
> 4. verity: telnet to M1S and and check the "post_init.sh" is exist.

I try this now 2 times. What a process :D

what I would like to achieve:
- add lumi.gateway.aeu01 to homeassistant
- in aqara-mode
- with cn aqara-country so that I can add the FP1 sensors.

I managed to get telnet to survive the change from xioami-mode to aqara-mode but when I followed the instructions "Not Flash modified firmware method (NOT for G2H, E1 hub, G3)" telnet did not survive the reboot.

At the second attempt, I tried to skip the reboot to have a tethered hack, but the device simply hung up after I following the instructions "Not Flash modified firmware method (NOT for G2H, E1 hub, G3)".

**Comment by kai-zer-ru** [comment]
https://dzen.ru/a/Zg5nNBHnsk6exK_f

**Comment by DrHooligun** [comment]
hi guys, need help
i have m1s eu lumi.gateway.aeu01
i clear telnet password by gw_global_tool.ttl via usb2ttl adapter
and when i try use flash custom firmware method i see error


m1s_update.sh revision: 2
type: lumi.gateway.aeu01, model: AH_M1S
This is not supported M1S and exit!

ty for your attention

**Comment by Nickolay40** [comment]
> https://dzen.ru/a/Zg5nNBHnsk6exK_f

It is for CN gateway!

**Comment by svflorin** [comment]
My situation is as follows

I have the `Aqara Hub M1S EU` / `HM1S-G01` / `lumi.gateway.aeu01` / `firmware 4.0.6_0001`

I have it in `MiHome` mode and I can enable `telnet` temporarily by `5222222` trick
<img width="863" height="506" alt="Image" src="https://github.com/user-attachments/assets/eb7ffc56-6919-4a29-8f4a-70746ac2392a" />

I have obtained the token using the `token_extractor.exe` 
<img width="1147" height="646" alt="Image" src="https://github.com/user-attachments/assets/6f61c843-89a3-46ee-87ea-b98b1ef5fae4" />

I tried Flash` M1S Custom firmware` method but it is not supported for EU hubs:
```
$cd /tmp && wget -O /tmp/curl "http://master.dl.sourceforge.net/project/mgl03/bin/curl?viasf=1" && chmod a+x /tmp/curl
$/tmp/curl -s -k -L -o /tmp/m1s_update.sh https://raw.githubusercontent.com/niceboygithub/AqaraM1SM2fw/main/modified/M1S/m1s_update.sh
$ chmod a+x /tmp/m1s_update.sh && /tmp/m1s_update.sh

m1s_update.sh revision: 2

type: lumi.gateway.aeu01, model: AH_M1S

This is not supported M1S and exit!
```

Via `telnet `I applied `Not Flash Custom firmware` method:
```
$ mkdir /data/bin
$ cd /data/bin
$ wget -O /data/bin/curl "http://master.dl.sourceforge.net/project/mgl03/bin/curl?viasf=1"
$ chmod +x /data/bin/curl
$ /data/bin/curl -s -k -L -o /data/bin/mosquitto https://raw.githubusercontent.com/niceboygithub/AqaraM1SM2fw/main/binutils/mosquitto
$ chmod a+x /data/bin/mosquitto

$ mkdir /data/scripts
$ cd /data/scripts
$ /data/bin/curl -s -k -L -o /data/scripts/post_init.sh 
https://raw.githubusercontent.com/niceboygithub/AqaraM1SM2fw/main/binutils/post_init.sh
$ chmod +x /data/scripts/post_init.sh

```

What I have in the `telnet` window after I input the commands but I'm not sure if I should have any other info displayed
```
# mkdir /data/bin
# cd /data/bin
# wget -O /data/bin/curl "http://master.dl.sourceforge.net/project/mgl03/bin/curl?viasf=1"
Connecting to master.dl.sourceforge.net (216.105.38.12:80)
curl                 100% |********************************************************************|  2271k  0:00:00 ETA
# chmod +x /data/bin/curl
# /data/bin/curl -s -k -L -o /data/bin/mosquitto https://raw.githubusercontent.com/niceboygithub/AqaraM1SM2fw/main/bi
nutils/mosquitto
# chmod a+x /data/bin/mosquitto
# mkdir /data/scripts
# cd /data/scripts
# /data/bin/curl -s -k -L -o /data/scripts/post_init.sh https://raw.githubusercontent.com/niceboygithub/AqaraM1SM2fw/
main/binutils/post_init.sh
# chmod +x /data/scripts/post_init.sh
```

At this point if I reboot I loose the `telnet` access and I need to to the `5222222` again.
The above steps were done in both `Aqara` and `MiHome` modes with the same results only difference being is `token_extractor.exe` is not working in `Aqara` mode

I have uncommented the `aeu01` lines in the `utils.py` file.

In `HA` I tried using the IP of the gateway in combinations with or without `telnet` and `token` also trying all the `M1S ` variants from the dropdown.

My `HA` is running in a virtual machine on a `Synology NAS`

Shortcomings:

I have no idea how to run the script below
```
#!/bin/sh

CUSTOM_POST_INIT=/data/scripts/post_init.sh
watching_post_init() {
    if [ ! -x ${CUSTOM_POST_INIT} ]; then
        mkdir -p /data/scripts/
        echo -e '#!/bin/sh\r\n\r\nfw_manager.sh -r\r\necho enable > /sys/class/tty/tty/enable\r\ntelnetd' > ${CUSTOM_POST_INIT}
        chmod a+x ${CUSTOM_POST_INIT}
    fi
}


main() {
    while [ 1 ]; do sleep 1; watching_post_init; done
}

main
```
