### ISSUE TITLE
Question: support of EU version of hubs

### ISSUE THREAD

**Issue by shift-del1** [niceboygithub/AqaraGateway#30]
Hi,

Planning to buy Aqara H1 EU switches, which are supported only on the EU server. Plan is to keep Aqara Home and HA support at the same time, if my understanding is correct, I will need a modified FW for this. Do you plan to add EU hub support to your integration, or do you have information if modified CN hub can work on EU server in Aqara Home and can control EU H1 switches (or any EU specific device)? Thank you.

**Comment by niceboygithub** [comment]
1. EU Hub with Mi home support, can be enabled telnet. Like M1S EU, then it can be supported in this integration later.
2. EU hub without Mi home support, it is not easy to enable telnet. 
3. CN hub with H1 EU switches. May use press 3 times button of CN hub a to pair with H1 EU hub. This need to test. According to my experience, US switches can be pair to CN hub by this way but only control in HA.

**Comment by shift-del1** [comment]
Thank you for your answer. Currently I'm talking about M1S, so yes, Mi Home support is available --> telnet can be enabled. If I want to use it with Aqara Home, I think I would need a custom FW, because I need to reset the M1S hub to switch mode to Aqara (instead of Mi) Home, so I would lose telnet, is that right? However I can't see an EU FW in your repository, that's why I asked if you plan to support it.
Regarding the different region for the hub and the server  I also have good experience with M1S EU device on CN server, but now I would need the opposite, as the H1 EU switches are available on EU server (and currently you support M1S CN only).

**Comment by niceboygithub** [comment]
1. if you switch hub to Aqara home mode, the telnet will be disabled.
2. My friend told that the firmware of M1S hub EU is signed. That’s mean it is not possible to have customize firmware without sign key.
3. For H1 EU switch, you can either try M1S CN in Aqara home mode, or M1S EU in Mi Home mode.

**Comment by shift-del1** [comment]
1. Thanks for confirmation, this is what I expected.
2. So M1S EU version is out of the game if I want Aqara Home and HA at the same time.
3. Ok, I'll  try to customize and put M1S CN on EU server to see if it works with H1 EU switch in both Aqara Home and HA.

Thank you for your support and for your work with the integration.
