### ISSUE TITLE
curl: line 1:  syntax error: unexpected "(" when trying to use it flashing M1S Custom firmware method

### ISSUE THREAD

**Issue by freginedevices** [niceboygithub/AqaraGateway#31]
I logged in as telnet root into my Aqara G2H
then i followed the instraction to flash M1S custom firmware.

Curl was downloaded to tmp dir but when i try to execute it with: 

`/tmp/curl -s -k -L -o /tmp/linux.bin https://raw.githubusercontent.com/niceboygithub/AqaraM1SM2fw/main/original/M1S/3.2.8_0009.0526//linux_3.2.8_0009.0526.bin`
it prompt me this error:
`curl: line 1:  syntax error: unexpected "("`

i tried to use other curl by different distro but same issue..

**Comment by niceboygithub** [comment]
> I logged in as telnet root into my Aqara G2H
> then i followed the instraction to flash M1S custom firmware.
>

You can not flash M1S firmware to G2H, They are different platform. 

> Curl was downloaded to tmp dir but when i try to execute it with:
> 
> `/tmp/curl -s -k -L -o /tmp/linux.bin https://raw.githubusercontent.com/niceboygithub/AqaraM1SM2fw/main/original/M1S/3.2.8_0009.0526//linux_3.2.8_0009.0526.bin`
> it prompt me this error:
> `curl: line 1: syntax error: unexpected "("`
> 
> i tried to use other curl by different distro but same issue..

Why you need to flash G2H firmware?

**Comment by freginedevices** [comment]
> You can not flash M1S firmware to G2H, They are different platform.
> 
according to some china website, the are the same
> Why you need to flash G2H firmware?
>
cause i want to test something.
By the way curl doesn't work and it's strange

**Comment by niceboygithub** [comment]
Which website?

they are totally different

**Comment by snakewa** [comment]
Hi there.
I wonder is it G2H is supported for Aqara Gateway integration? Currently the device is only added but no integration (no new entity or anything) . Acording to Aqara Gateway , there is the manually process to add "curl" and "mosquitto"

```
cd /data/bin
wget -O /data/bin/curl "http://master.dl.sourceforge.net/project/mgl03/bin/curl?viasf=1"
chmod +x /data/bin/curl
/data/bin/curl -s -k -L -o /data/bin/mosquitto https://raw.githubusercontent.com/niceboygithub/AqaraM1SM2fw/main/binutils/mosquitto
chmod a+x /data/bin/mosquitto

mkdir /data/scripts
cd /data/scripts
/data/bin/curl -s -k -L -o /data/scripts/post_init.sh https://raw.githubusercontent.com/niceboygithub/AqaraM1SM2fw/main/binutils/post_init.sh
chmod +x /data/scripts/post_init.sh
```

I know it is for m1s, I found mosquitoo in https://github.com/niceboygithub/AqaraCameraHubfw , but not curl and post_init.sh

Just want to make sure current status of G2H support.

Thanks for you great work anyway, evne though G2H is support or not.

**Comment by niceboygithub** [comment]
> Hi there.
> I wonder is it G2H is supported for Aqara Gateway integration? Currently the device is only added but no integration (no new entity or anything) . Acording to Aqara Gateway , there is the manually process to add "curl" and "mosquitto"
> 
> ```
> cd /data/bin
> wget -O /data/bin/curl "http://master.dl.sourceforge.net/project/mgl03/bin/curl?viasf=1"
> chmod +x /data/bin/curl
> /data/bin/curl -s -k -L -o /data/bin/mosquitto https://raw.githubusercontent.com/niceboygithub/AqaraM1SM2fw/main/binutils/mosquitto
> chmod a+x /data/bin/mosquitto
> 
> mkdir /data/scripts
> cd /data/scripts
> /data/bin/curl -s -k -L -o /data/scripts/post_init.sh https://raw.githubusercontent.com/niceboygithub/AqaraM1SM2fw/main/binutils/post_init.sh
> chmod +x /data/scripts/post_init.sh
> ```
> 
> I know it is for m1s, I found mosquitoo in https://github.com/niceboygithub/AqaraCameraHubfw , but not curl and post_init.sh
> 
> Just want to make sure current status of G2H support.
> 
> Thanks for you great work anyway, evne though G2H is support or not.

For G2H, you donot need to replace mosquitto. 
The only step is to enable telnet. AqaraGateway component  supports G2H
