### ISSUE TITLE
Can it work with M1S EU version (lumi.gateway.aeu01)?

### ISSUE THREAD

**Issue by mrtxilya** [niceboygithub/AqaraGateway#34]
Hello! 
I did everything succesfully according to the instructions: https://gist.github.com/InsaneWookie/1221cd6267745ea3c16f6a2a83ba3a44

But when I try to add Aqara Hub integration in Home Assistant, I got 'Cancelled' message.
Is there a way to add M1S EU hub to Home Assistant?

**Comment by niceboygithub** [comment]
Please see [this](https://github.com/niceboygithub/AqaraGateway/issues/29#issuecomment-889136414)

**Comment by mrtxilya** [comment]
Thank you! It works!

Also I changed lines 1248, 1255 in utils.py to get the light works.
`if 'lumi.gateway.acn01' in model or 'lumi.gateway.aeu01' in model:`

Now I have a visual bug when I set the light brightness.
When I set 100% brightness it succesfully sets on Hub, but the slider in Home Assistant jumps back to 39%
![image](https://user-images.githubusercontent.com/36232079/132254199-0af42598-2d95-452b-a482-7a8cebb124c4.png)

I think slider in Home Assistant has 0..255 interval. When I set value 255 in Developer Panel the slider get full.
Can you help to fix it?

**Comment by Napalmcold** [comment]
> return int(self._brightness * 2.55)

Could you please tell what exactly I should replace with that string? After replacing 83 line the light entity becomes unavailable
