### ISSUE TITLE
works in x86_64, but not work in armv7l

### ISSUE THREAD

**Issue by woyaya** [niceboygithub/AqaraGateway#35]
Very strange phenomenon with hardware: Aqara gateway M1S (ZHWG15LM)

The integration works great with latest homeassistant @ x86_64 platform。

## System Health

version | core-2021.9.4
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.11.0-34-generic
arch | x86_64
timezone | Asia/Shanghai

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4957
Installed Version | 1.15.2
Stage | running
Available Repositories | 880
Installed Repositories | 6

</details>

<details><summary>Aqara Gateway</summary>

telnet_logged | 10.100.0.37

-- | --
mqtt_connected | 10.100.0.37

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | pending

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Ubuntu 20.04.2 LTS
-- | --
update_channel | stable
supervisor_version | supervisor-2021.09.0
docker_version | 20.10.7
disk_total | 82.0 GB
disk_used | 15.7 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Zigbee2mqtt (1.21.1-1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 2
mode | storage

</details>

But not work with latest homeassistant @ armv7l platform（Raspberry Pi 4 Model B Rev 1.1）

version | core-2021.8.6
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.17-v7l+
arch | armv7l
timezone | Asia/Shanghai

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.15.1
Stage | running
Available Repositories | 889
Installed Repositories | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 4
views | 3
mode | storage

</details>

The integration reports following info
```
Unknown error occurred
```

and log of homeassistant(with homeassistant config `logger::custom_components.aqara_gateway: debug`)
```
2021-09-14 19:33:23 INFO (MainThread) [custom_components.aqara_gateway.core.utils] lumi.gateway.acn01 3.1.3_0002 Linux detected
2021-09-14 19:34:27 INFO (MainThread) [homeassistant.setup] Setting up aqara_gateway
2021-09-14 19:34:27 INFO (MainThread) [homeassistant.setup] Setup of domain aqara_gateway took 0.0 seconds
2021-09-14 19:34:27 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 673, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 650, in _send_frame
    self._write(header + message)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 660, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2021-09-14 19:34:27 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 673, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 650, in _send_frame
    self._write(header + message)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 660, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2021-09-14 19:34:27 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [2797600720] Connection closed by client
2021-09-14 19:34:27 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [2771019280] Connection closed by client
```

What could cause this problem？
Thanks！

**Comment by niceboygithub** [comment]
The error log is not related to AqaraGateway.

The possible problem is that can not telnet to M1S from Raspberry Pi.

**Comment by woyaya** [comment]
> The error log is not related to AqaraGateway.

Every time I configure the integration, HA will output this information
How to make the integration output more information？(I have configured custom_components.aqara_gateway: debug)

> 
> The possible problem is that can not telnet to M1S from Raspberry Pi.

I telnet to M1S, and confirmed mosquitto already worked. 
and confirmed that the Raspberry Pi has established a telnet connection with the M1S when I configure the integration, but the connection will be disconnected soon
Following lines are the output of netstat
```
# netstat -anp | grep "10.100.0.58\|mosquitto"
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      1287/mosquitto
tcp        0      0 127.0.0.1:1883          127.0.0.1:55780         ESTABLISHED 1287/mosquitto
tcp        0      0 10.100.0.37:1883        10.100.10.100:47261     ESTABLISHED 1287/mosquitto
tcp        0      0 10.100.0.37:1883        10.100.10.100:53461     ESTABLISHED 1287/mosquitto
tcp        0      0 127.0.0.1:1883          127.0.0.1:55779         ESTABLISHED 1287/mosquitto
tcp        0      0 127.0.0.1:1883          127.0.0.1:55778         ESTABLISHED 1287/mosquitto
tcp        0      0 :::1883                 :::*                    LISTEN      1287/mosquitto
tcp        0      0 ::ffff:10.100.0.37:23   ::ffff:10.100.0.58:38404 ESTABLISHED 1050/telnetd
```

   M1S: 10.100.0.37
   x86_64: 10.100.10.100
   Raspberry Pi: 10.100.0.58

**Comment by niceboygithub** [comment]
> and confirmed that the Raspberry Pi has established a telnet connection with the M1S when I configure the integration, but the connection will be disconnected soon


You need find the cause of disconnection

**Comment by woyaya** [comment]
Finally found the cause of the problem
The topology of homeassistant @ armv7l is like this
nginx<-->homeassistant
aqara_gateway::async_step_user is blocked for too much time, which causes homeassistant to fail to respond to nginx's ping-pong request, nginx thinks upstream(homeassistant) timed out and disconnected(but I don’t know why disconnection will cause aqara_gateway configuration failure)

So, **if you use a proxy such as nginx/apache on your system, do NOT use it when configuring aqara_gateway, but directly visit homeassistant (port 8123)**
