### ISSUE TITLE
Aqara Locker D100 support

### ISSUE THREAD

**Issue by dik111** [niceboygithub/AqaraGateway#36]
Hi @niceboygithub  Thanks for your great efforts,
Can you please add Aqara Locker D100 (ZNMS20LM) support?

**Comment by niceboygithub** [comment]
D100 is only BT supported. Can not support here.

**Comment by dik111** [comment]
> D100 is BT only. Can not support here.
Thanks a lot, I can only find another way to solve this problem. T T

**Comment by niceboygithub** [comment]
You try xiaomi gateway3.
https://github.com/AlexxIT/XiaomiGateway3

**Comment by jasonfonghk** [comment]
> D100 is BT only. Can not support here.

Hello, it has a Aqara D100 zigbee version for oversea, I would like to ask any chance to support it? thanks.
https://www.aqara.com/en/product/smart-door-lock-d100-zigbee/

**Comment by dankarization** [comment]
Isn't it advertised as zigbee one with 2 protocols? 
![image](https://github.com/niceboygithub/AqaraGateway/assets/26330178/500208be-e2f5-4528-9628-06d3d997572b)
![image](https://github.com/niceboygithub/AqaraGateway/assets/26330178/970354c2-d643-4d8a-97c8-ae2afc7b2779)

**Comment by afghifariii** [comment]
@dankarization @niceboygithub I think there are 2 versions of D100. One with BT only & the latest one with BT & Zigbee 3.0 support (which realesed in 2022).i think for The zigbee versions it will be very similar to A100, it just different model. If you have the device, could you test it?

here is the link https://www.aqara.com/en/aqara-announces-fully-automatic-smart-door-lock-d100-zigbee/

**Comment by dankarization** [comment]
I have access to zigbee and bluetooth version of D100. What should I need to test?

**Comment by niceboygithub** [comment]
Enable the mqtt log of AqaraGateway Then save the logs, send the logs to me.

**Comment by dankarization** [comment]
Ok, I will do this in a couple of weeks and get back to you

**Comment by niceboygithub** [comment]
The most important is that you need to record the time of action(open the door, close the door, who open the door, it will be better with detail information

**Comment by jasonfonghk** [comment]
The zigbee verison D100 is `aqara.lock.aqgl01`,
I am using it.

**Comment by afghifariii** [comment]
@jasonfonghk are you able to see the device in home assistant ? If not could you get the logs like @niceboygithub mentioned?

**Comment by jasonfonghk** [comment]
> @jasonfonghk are you able to see the device in home assistant ? If not could you get the logs like @niceboygithub mentioned?

Yes, I am using D100 zigbee in home assistant.
I have forked and modified the code to supoort it.

**Comment by afghifariii** [comment]
@jasonfonghk could you share what you’ve done, so @niceboygithub could probably add that to the next release. I Also plan to buy this lock and it seems a bit hard to get more info. Thanks in advance!

**Comment by jasonfonghk** [comment]
> @jasonfonghk could you share what you’ve done, so @niceboygithub could probably add that to the next release. I Also plan to buy this lock and it seems a bit hard to get more info. Thanks in advance!

Yes, the code is in my github account.

BTW, Do you have hacked aqara hub?
If you plan to use Aqara D100 zigbee in homeassistant, the most important part is the hacked aqara hub to use AqaraGateway integration.

**Comment by afghifariii** [comment]
@jasonfonghk not at the moment. I know that it needs a hacked version of aqara hub. I also plan to buy the E1 CN hub. Should be enough right?

**Comment by jasonfonghk** [comment]
> @jasonfonghk not at the moment. I know that it needs a hacked version of aqara hub. I also plan to buy the E1 CN hub then follow the instructions from README file to do the soft_hack. Should be enough right?

I am also using E1 CN hub,
it is easy to soft hack via Mi mode token,
then change to Aqara mode with hacked status.

The most tricky part is the Aqara App "region",
You need to modify the E1 CN to E1 EU(global),
The you can use Aqara App (global region) to add the Aqara D100 zigbee door lock. 
(If you use the Aqara App CN region, it cannot add the D100 zigbee door lock)

ref: https://github.com/niceboygithub/AqaraGateway/issues/56

**Comment by afghifariii** [comment]
@jasonfonghk got it. Thanks a lot for thr detailed informations. So, the version of the code in your git not only add the D100 but also add the E1 Hub EU (CN hacked)?

**Comment by mikechouto** [comment]
@jasonfonghk Thanks for all your work, wondering if it'll be possible for you to submit a PR so that it can be merged here ? Thanks.

**Comment by ARoussakov** [comment]
@jasonfonghk **Aqara Smart Door Lock D100 Lock Event** don't make a diference between unlok from inside or outside. Both hase state **"The door is unlocked"**. But Aqara can make the diffirence, from there it was unlocked. It also has state **"Unlocked with NFC by user"**, but nothing special for Fingerprit. And if case, if only one user use NFC card, **Aqara Smart Door Lock D100 Key Id** state is not changing, and automation with changing this state is not running.
