### ISSUE TITLE
Add support for H100

### ISSUE THREAD

**Issue by gnep88** [niceboygithub/AqaraGateway#37]
Niceboy, thank you so much for the nice work!

could you please add support for the latest flagship door lock H100 (camera, zigbee, WiFi, ble, fully automatic)

New device:
did: lumi.xxxxxxxxxxxxxxxx
mac: xxxxxxxxxxxxxxxx
model: aqara.lock.dacn03
version: 0.0.0_0001
zb_ver: 3.0
joined_type: 1

link
https://www.aqara.com/cn/productDetail/smart-door-lock-h100

thanks again !

**Comment by gnep88** [comment]
Tried to add this one in the lock_data.py but the lock still does not appear under the gateway

    "aqara.lock.dacn03": (
        WITH_LI_BATTERY | SUPPORT_ALARM |
        SUPPORT_DOORBELL | SUPPORT_WIFI | SUPPORT_CAMERA)

**Comment by niceboygithub** [comment]
Please provide the logs of h100.

**Comment by gnep88** [comment]
I am working on it under a fork for H100
https://github.com/gnep88/AqaraGateway

Some basic functions already supported. I will contribute the changes once it is done.

**Comment by qwt2003** [comment]
> 

Hi, it’s been a long time since we discussed this lock. I have an idea, if we control the lock via zigbee is not safety, how about we just obtain the door lock status in order to make the automation? We can use these status as conditions for arrived  or leave home’s automation, e.g. unlock with button means open door from inside=leave home, unlock with fingerprint/nfc/password/keys=arrived home, unlock with temp password=visitor arrived, etc.

**Comment by gnep88** [comment]
> @gnep88
> 
> Hi, it’s been a long time since we discussed this lock. I have an idea, if we control the lock via zigbee is not safety, how about we just obtain the door lock status in order to make the automation? We can use these status as conditions for arrived or leave home’s automation, e.g. unlock with button means open door from inside=leave home, unlock with fingerprint/nfc/password/keys=arrived home, unlock with temp password=visitor arrived, etc.
> 
> > > > I am working on it under a fork for H100 https://github.com/gnep88/AqaraGateway
> > > > Some basic functions already supported. I will contribute the changes once it is done.
> > > 
> > > 
> > > Hi, recently I contacted with Aqara dev team, got some info about this lock.
> > > First, the lock and unlock function in homekit is based on BLE through home hub(AppleTV, HomePod, IPad), not on zigbee through gateway. They said use this way because of HomeKit Accessory Protocol restrict the lock accessories' working condition. So if someone have a big house or the lock out of home hub's BLE range will cause "Lock No Responding" problem, the solution is set another home hub accessory nearby (NOT CONFIRM YET).
> > > Secondly, they will try to make the basic function with zigbee through gateway, but according to their security evaluation, this way will caused some breaches so it will be a long dev progress.
> > > Hopes these usefully.
> > 
> > 
> > Thanks for the information. This means for now let us focus on the read-only status and properties of the lock.
> > In the meantime, looking forward to use zigbee to control the lock.

Ok. Let me first release some very basic functions of H100: Door status, fingerprint ID
I created a pull request for this.

**Comment by Djeloan** [comment]
Sorry for asking here, but is Aqara n200 supported for m1s? Im planning on buying it soon and was wondering if it works..
