### ISSUE TITLE
Can not found Button in Single and Double Wall Button E1(lumi.remote.acn004)

### ISSUE THREAD

**Issue by dik111** [niceboygithub/AqaraGateway#39]
Hi @niceboygithub:
  I updated AparaGateway to version 0.08. I have been able to find E1  Single button switch (lumi.remote.acn003) and E1 Double button switch (lumi.remote.acn004) on HA, but I can’t seem to find the button.

![image](https://user-images.githubusercontent.com/34541162/134612660-545d9748-3969-4127-87f9-dddbbd1d3b08.png)

**Comment by niceboygithub** [comment]
You can detect/montior the button action in action sensor.

**Comment by dik111** [comment]
> You can detect/montior the button action in action sensor.

the button action in action sensor is unknow - -!
