### ISSUE TITLE
an unsupported modell: lumi.light.cwacn1

### ISSUE THREAD

**Issue by miniknife88** [niceboygithub/AqaraGateway#4]
Aqara 0-10v dimmer [ZNTGMK12LM]
model: lumi.light.cwacn1

With brightness and color temperature adjustment function

log:
`2021-02-28 19:04:10  DEBUG  gateway  192.168.1.51: MQTT on_message: zigbee/send {"cmd":"write_ack","id":1949,"did":"lumi.4cf8cdf3c7d74e7","dev_src":"0","time":1614510250340,"rssi":-53,"zseq":6,"params":[{"res_name":"4.1.85","value":1}]}
 2021-02-28 19:04:10  DEBUG  gateway  192.168.1.51: MQTT on_message: zigbee/send {"cmd":"report","id":1949,"did":"lumi.4cf8cdf3c7d74e7","time":1614510250413,"rssi":-49,"zseq":6,"params":[{"res_name":"4.1.85","value":1}],"dev_src":"0"}
2021-02-28 19:04:12  DEBUG  gateway  192.168.1.51: MQTT on_message: zigbee/send {"cmd":"report","id":2000004740,"did":"lumi.4cf8cdf3c7d74e7","time":1614510252043,"rssi":-49,"zseq":23,"params":[{"res_name":"14.1.85","value":98}],"dev_src":"0"}`

**Comment by miniknife88** [comment]
Aqara motion sensor T1 [RTCGQ12LM] 
model: lumi.motion.agl02

With illuminance motion sensor
With custom occupancy timeout （3 seconds minimum）

log:
`2021-02-28 19:10:04  DEBUG  gateway  192.168.1.51: MQTT on_message: zigbee/send {"cmd":"heartbeat","id":2000004763,"time":1614510604477,"rssi":-49,"params":[{"did":"lumi.4cf8cdf3c7fecc2","time":1614510604477,"zseq":44,"res_list":[{"res_name":"8.0.2008","value":3099},{"res_name":"8.0.2006","value":25},{"res_name":"8.0.2011","value":1},{"res_name":"8.0.2010","value":3},{"res_name":"8.0.2012","value":10},{"res_name":"8.0.2013","value":1},{"res_name":"8.0.2002","value":10},{"res_name":"8.0.2003","value":399},{"res_name":"8.0.2004","value":0},{"res_name":"8.0.2005","value":0},{"res_name":"8.0.2033","value":0},{"res_name":"8.0.2022","value":35},{"res_name":"8.0.2023","value":1},{"res_name":"8.0.2036","value":54108},{"res_name":"3.1.85","value":0},{"res_name":"0.3.85","value":9},{"res_name":"8.0.2173","value":3},{"res_name":"8.0.2175","value":1},{"res_name":"8.0.2174","value":168},{"res_name":"8.0.2007","value":90}]}]}`

**Comment by niceboygithub** [comment]
I don't have such sensors, and can not test them after added.
If you help to test them, it will be great.
https://github.com/niceboygithub/AqaraGateway/commit/3768e531b0db7ebcd200e55c620811914145d624

**Comment by miniknife88** [comment]
Aqara 0-10v dimmer [ZNTGMK12LM]
model: lumi.light.cwacn1

This device has a color temperature attribute

I will always follow the project and help you test！
