### ISSUE TITLE
aqara hub m2

### ISSUE THREAD

**Issue by matteos1** [niceboygithub/AqaraGateway#42]
is there a guide or video explaining how to open telnet on gateway m2? Thank you

**Comment by niceboygithub** [comment]
If you are using gateway M2 EU, I have no way to enable telnet on M2 EU.

**Comment by niceboygithub** [comment]
![94F229AF-2395-4EEF-A2B6-BD4EA2E2D68C](https://user-images.githubusercontent.com/74046071/135677475-40e1abc2-e2a0-4d44-a764-f768f0d00c27.jpeg)

1. UART connection 
2. Execute AqaraGateway.exe
3. Choose firmware, config M2, rootfs_0, COM port
4. Click Flash.
5. Plug-in power cable. then wait for 11mins

**Comment by matteos1** [comment]
yes i have m2 eu. so this is not possible?

**Comment by niceboygithub** [comment]
> yes i have m2 eu. so this is not possible?

Not possible. M2 EU has signed firmware

**Comment by STUkh** [comment]
@niceboygithub hey! Thanks for you work. Could you please share the way how to disassemble Aqara M2 hub? A bit stuck with this part and won't damage it a lot.
