### ISSUE TITLE
Aqara Cube states unknown

### ISSUE THREAD

**Issue by Nicras** [niceboygithub/AqaraGateway#43]
Hi, I managed to add Aqara Hub M1S EU-Version and it seems to work until now.
I have a Cube connected to my Hub and it is also in HA as a binary sensor but only a few of the gestures are fine.
So far I've seen flip90, flip180 and rotate. The double knock and shake are recognized but HA shows Unknown.
It would be really cool, if you can expand the features of the cube.

Thanks in advance

**Comment by xquyan** [comment]
also there's this "free fall" state that is shown as unknown, it's not shown in the aqara home app but is shown when connected through ZHA; and it seems so in the app that it should be able to recognize the direction and angle that it rotated. Might want to consider adding these too
