### ISSUE TITLE
Can Aqara m1s 2022 version be supported？

### ISSUE THREAD

**Issue by mikeinblue** [niceboygithub/AqaraGateway#45]

**Comment by shift-del1** [comment]
I have the M1S CN version, no sign of 2022 on the gateway or on its box. Mi Home recognized it as original M1S, while Aqara Home identified it as M1S 2022 version. AqaraGateway worked properly, except the scale of the brightness, like having a scale from 0 to 255, but you can adjust it between 1 and 100 only (there is an open issue mentioning the same).
