### ISSUE TITLE
The new Aqara Door Sensor E1's state is wrong

### ISSUE THREAD

**Issue by mikeinblue** [niceboygithub/AqaraGateway#46]
I bought new Aqara Door Sensor E1 this week.   And I found 2 issues.  
1.The contact's state is reverse，when the door is open, it displays shut. When the door is closed,  it shows open.But in mihome and homekit ,it's correct.
2.The contact's battery shows unknow.

Let me know what you need,

THX for your time.

**Comment by mikeinblue** [comment]
I am a newbie. It would be nice if you can tell me how to get the log.

**Comment by niceboygithub** [comment]
Please try the latest code.

**Comment by mikeinblue** [comment]
> Please try the latest code.

The state is correct now, thank you . The battery is still unkown.

**Comment by mikeinblue** [comment]
With the latest master branch.It was fixed.Thx so much.
