### ISSUE TITLE
My m1s can't be  contrled by hass.

### ISSUE THREAD

**Issue by mikeinblue** [niceboygithub/AqaraGateway#47]
**_My m1s can't be  contrled by hass.
There is my operation:  arm away, disarm, arm night , disarm, turn on the light, turn off light. After all these operations the m1s didn't change any thing. M1S's mifw is 3.1.6_022 mihome.
Here is the log:_**

> 2021-10-26 12:11:47 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: broker/ping {"cmd":"ping","id":4420,"did":"lumi.0","dev_src":"0","time":1635221506035}
> 2021-10-26 12:11:50 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":25088,"type":"rgb","ver":1}
> 2021-10-26 12:11:50 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":29184,"type":"rgb","ver":1}
> 2021-10-26 12:11:50 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"behave","data":{"blue":0,"duration":-1,"green":0,"off_period":200,"on_period":100,"persist":false,"post_delay":200,"pre_delay":200,"red":77,"repeat":3},"id":33280,"type":"rgb","ver":1}
> 2021-10-26 12:11:52 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":38145,"type":"rgb","ver":1}
> 2021-10-26 12:11:52 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":42241,"type":"rgb","ver":1}
> 2021-10-26 12:11:52 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/send {"ver":1,"type":"rgb","cmd":"behaved","id":33280}
> 2021-10-26 12:11:52 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":45569,"type":"rgb","ver":1}
> 2021-10-26 12:11:52 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":49665,"type":"rgb","ver":1}
> 2021-10-26 12:11:52 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"behave","data":{"blue":0,"duration":-1,"green":77,"off_period":200,"on_period":100,"persist":false,"post_delay":200,"pre_delay":200,"red":0,"repeat":3},"id":53761,"type":"rgb","ver":1}
> 2021-10-26 12:11:53 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":58625,"type":"rgb","ver":1}
> 2021-10-26 12:11:54 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":62721,"type":"rgb","ver":1}
> 2021-10-26 12:11:54 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/send {"ver":1,"type":"rgb","cmd":"behaved","id":53761}
> 2021-10-26 12:11:54 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":512,"type":"rgb","ver":1}
> 2021-10-26 12:11:54 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":4608,"type":"rgb","ver":1}
> 2021-10-26 12:11:54 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"behave","data":{"blue":0,"duration":-1,"green":0,"off_period":200,"on_period":100,"persist":false,"post_delay":200,"pre_delay":200,"red":77,"repeat":3},"id":8704,"type":"rgb","ver":1}
> 2021-10-26 12:11:55 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":13569,"type":"rgb","ver":1}
> 2021-10-26 12:11:55 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":17665,"type":"rgb","ver":1}
> 2021-10-26 12:11:55 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/send {"ver":1,"type":"rgb","cmd":"behaved","id":8704}
> 2021-10-26 12:11:56 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":20993,"type":"rgb","ver":1}
> 2021-10-26 12:11:56 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":25089,"type":"rgb","ver":1}
> 2021-10-26 12:11:56 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"behave","data":{"blue":0,"duration":-1,"green":77,"off_period":200,"on_period":100,"persist":false,"post_delay":200,"pre_delay":200,"red":0,"repeat":3},"id":29185,"type":"rgb","ver":1}
> 2021-10-26 12:11:57 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":34049,"type":"rgb","ver":1}
> 2021-10-26 12:11:57 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":38145,"type":"rgb","ver":1}
> 2021-10-26 12:11:57 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/send {"ver":1,"type":"rgb","cmd":"behaved","id":29185}
> 2021-10-26 12:12:07 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: broker/ping {"cmd":"ping","id":4421,"did":"lumi.0","dev_src":"0","time":1635221526035}
> 2021-10-26 12:12:08 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"type":"rgb","rev":1,"id":22455}
> 2021-10-26 12:12:10 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"type":"rgb","rev":1,"id":11945}
> 2021-10-26 12:12:12 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: zigbee/send {"cmd":"report","id":2000002049,"did":"lumi.0","time":1635221531050,"rssi":-62,"zseq":0,"params":[{"res_name":"0.3.85","value":39}],"dev_src":"0"}

_**Then I did the same operation through mihome,the m1s changed state very quickly,the logs is below:**_

> 2021-10-26 12:14:27 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: broker/ping {"cmd":"ping","id":4428,"did":"lumi.0","dev_src":"0","time":1635221666095}
> 2021-10-26 12:14:32 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":41472,"type":"rgb","ver":1}
> 2021-10-26 12:14:32 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":45568,"type":"rgb","ver":1}
> 2021-10-26 12:14:32 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"behave","data":{"blue":0,"duration":-1,"green":0,"off_period":200,"on_period":100,"persist":false,"post_delay":200,"pre_delay":200,"red":77,"repeat":3},"id":49664,"type":"rgb","ver":1}
> 2021-10-26 12:14:33 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":54529,"type":"rgb","ver":1}
> 2021-10-26 12:14:33 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":58625,"type":"rgb","ver":1}
> 2021-10-26 12:14:33 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/send {"ver":1,"type":"rgb","cmd":"behaved","id":49664}
> 2021-10-26 12:14:34 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":61953,"type":"rgb","ver":1}
> 2021-10-26 12:14:34 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":513,"type":"rgb","ver":1}
> 2021-10-26 12:14:34 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"behave","data":{"blue":0,"duration":-1,"green":77,"off_period":200,"on_period":100,"persist":false,"post_delay":200,"pre_delay":200,"red":0,"repeat":3},"id":4609,"type":"rgb","ver":1}
> 2021-10-26 12:14:35 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":9473,"type":"rgb","ver":1}
> 2021-10-26 12:14:35 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":13569,"type":"rgb","ver":1}
> 2021-10-26 12:14:35 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/send {"ver":1,"type":"rgb","cmd":"behaved","id":4609}
> 2021-10-26 12:14:35 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":16896,"type":"rgb","ver":1}
> 2021-10-26 12:14:35 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":20992,"type":"rgb","ver":1}
> 2021-10-26 12:14:35 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"behave","data":{"blue":0,"duration":-1,"green":0,"off_period":200,"on_period":100,"persist":false,"post_delay":200,"pre_delay":200,"red":77,"repeat":3},"id":25088,"type":"rgb","ver":1}
> 2021-10-26 12:14:37 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":29953,"type":"rgb","ver":1}
> 2021-10-26 12:14:37 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":34049,"type":"rgb","ver":1}
> 2021-10-26 12:14:37 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/send {"ver":1,"type":"rgb","cmd":"behaved","id":25088}
> 2021-10-26 12:14:37 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":37377,"type":"rgb","ver":1}
> 2021-10-26 12:14:37 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":41473,"type":"rgb","ver":1}
> 2021-10-26 12:14:37 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"behave","data":{"blue":0,"duration":-1,"green":77,"off_period":200,"on_period":100,"persist":false,"post_delay":200,"pre_delay":200,"red":0,"repeat":3},"id":45569,"type":"rgb","ver":1}
> 2021-10-26 12:14:38 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":50433,"type":"rgb","ver":1}
> 2021-10-26 12:14:38 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":54529,"type":"rgb","ver":1}
> 2021-10-26 12:14:38 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/send {"ver":1,"type":"rgb","cmd":"behaved","id":45569}
> 2021-10-26 12:14:40 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":87,"breath":500,"green":27,"red":59},"id":58625,"type":"rgb","ver":1}
> 2021-10-26 12:14:42 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: ioctl/recv {"cmd":"control","data":{"blue":0,"breath":500,"green":0,"red":0},"id":62721,"type":"rgb","ver":1}
> 2021-10-26 12:14:47 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.22.157: MQTT on_message: broker/ping {"cmd":"ping","id":4429,"did":"lumi.0","dev_src":"0","time":1635221686105}
> 

**Hope can help you**

**Comment by niceboygithub** [comment]
Alarm control is known issue.

**Comment by mikeinblue** [comment]
OK, I got it. Thank for your time.
