### ISSUE TITLE
Can m2 ir be used in home assistant?

### ISSUE THREAD

**Issue by Leiseya** [niceboygithub/AqaraGateway#48]
I  want to buy a m2 and ues its IR to control my other IR deveces in home assistant. But I don't know if I can use this fw to learn and send IR in home assistant. 
Thanks

**Comment by niceboygithub** [comment]
Unfortunately,  I can not find any commands to control IR. So can not control M2 IR from HA.

**Comment by Leiseya** [comment]
Thank you very much for your reply.
