### ISSUE TITLE
Does this work with Aqara Hub M1S, model lumi.gateway.aqhm02?

### ISSUE THREAD

**Issue by tudorbordei** [niceboygithub/AqaraGateway#49]
I tried all the config steps, but i got stuck at enabling Telnet. After running the enable telnet command the hub froze. Any other command sent to it returned the message "Error: Unable to discover the device" and in Mi Home it's showing as Offline.
Any help would be highly appreciated.

**Comment by niceboygithub** [comment]
aqhm02 is Aqara Gateway M1, not M1S.
