### ISSUE TITLE
Is there any way to integrate Aqara G2?

### ISSUE THREAD

**Issue by binakot** [niceboygithub/AqaraGateway#51]
I know that `G2H` works. But what about `G2`? Is it useless toy? ;(

**Comment by niceboygithub** [comment]
G2 did not mqtt, so not support.
BUT you can add rtsp support. Then have webrtc in HA

**Comment by binakot** [comment]
Thanks for quick answer :)

Without `mqtt` this device is almost useless for me 😞 
So large difference between G2H and G2. I didn't know that.
