### ISSUE TITLE
Support fo Aqara Mini-Switch

### ISSUE THREAD

**Issue by kv1296** [niceboygithub/AqaraGateway#54]
Hello,
Amazing job creating this project. 

Could you please add support for the Aqara Wireless Mini-Switch Model# WXKG11LM? So that automations can be triggered using the single press, double press, and long-press commands?

Currently, this is how it presents:
<img width="1151" alt="Screen Shot 2021-11-23 at 3 34 09 PM" src="https://user-images.githubusercontent.com/45614017/143102263-94cee898-041f-4ec7-9e14-7dab6ca725c1.png">

The switch does trigger events properly like this:

```
    "event_type": "xiaomi_aqara.click",
    "data": {
        "entity_id": "binary_sensor.0x158d0006d4d79e_switch",
        "click_type": "single"

    "event_type": "xiaomi_aqara.click",
    "data": {
        "entity_id": "binary_sensor.0x158d0006d4d79e_switch",
        "click_type": "double"

    "event_type": "xiaomi_aqara.click",
    "data": {
        "entity_id": "binary_sensor.0x158d0006d4d79e_switch",
        "click_type": "hold"
```

It would be nice if these were specified actions for the device through your plugin. Thanks!

**Comment by niceboygithub** [comment]
It was already supported. You can take following example in automation.

```
platform: state
entity_id: binary_sensor.0x158d00035999fa_switch
to: single
id: single
```

**Comment by shaokaollu** [comment]
> It was already supported. You can take following example in automation.
> 
> ```
> platform: state
> entity_id: binary_sensor.0x158d00035999fa_switch
> to: single
> id: single
> ```

I have the same problem with aqara double rocker WXKG02LM, this is what I get from HA. I don't know how to select between short press, long press ect. Thanks!
![2021-12-15 05_43_03-Developer Tools - Home Assistant](https://user-images.githubusercontent.com/38537984/146125274-a59e4352-4a99-4347-873c-1ac9af13c707.jpg)
