### ISSUE TITLE
help needed with M1S (eu) after disconnect from the wireless and unable to reconnect

### ISSUE THREAD

**Issue by SNIPER722** [niceboygithub/AqaraGateway#55]
I follow the instruction here and success after a few tries.
https://gist.github.com/InsaneWookie/1221cd6267745ea3c16f6a2a83ba3a44
info:
NAME: Aqara Hub M1S
MODEL: `lumi.gateway.aeu01`
with `Not Flash Custom firmware method`
original setup is Mi Home mode on cn server. (register on cn server and retrieve the token there)

and after one night the wifi is unable to connect. so I reset the device 
current symptoms:
after setup with homekit, it take the connection information . and connect to the wireless. telnet can be connected during the setup process. when the process timeout/failed it cut the wireless connection and drop the telnet connection.
voice promote is "failed to bind to account"
I tried both Aqara and Mi Home mode. and no change son the wifi network
any help is appreciated

**Comment by niceboygithub** [comment]
First, EU version shall not work in CN server.

You can change other internet network then try again.

**Comment by SNIPER722** [comment]
that seems the only point I missed. it is working now.

thanks
