### ISSUE TITLE
Question: Aqara hub E1 CN in Aqara app on EU server.

### ISSUE THREAD

**Issue by Cassiopea1** [niceboygithub/AqaraGateway#56]
Hi, has anyone managed to add an Aqara hub E1 CN version in the Aqara app on an EU server? Thanks.

**Comment by rezmus** [comment]
root hub in mijia, switch to aqara mode, change model from aqcn02 to aqcn03, connect to eu region in aqara app.

**Comment by Cassiopea1** [comment]
Nice. Thank you. What is the procedure to change model number from aqn02 to aqn03?

**Comment by rezmus** [comment]
get permanent root/telnet in mijia mode. switch to aqara mode
```
fw_manager.sh -s &
```
connect to hub ap, telnet to hub
```
asetprop persist.sys.model "lumi.gateway.aqcn03"
reboot -f
```

**Comment by Cassiopea1** [comment]
Hi again. I tried to do what you wrote, but something went wrong.
1. I've flashed the fw from [https://github.com/niceboygithub/AqaraGateway]
2. If I switch to aqara mode and try to telnet into the hub I'm getting "No permission"
3. If, still in mijia mode, I telnet into the hub and run "fw_manager.sh -s &" I'm getting:

`Aqara-Hub-E1-8044 login: root
Password:
login: can't chdir to home directory '/home/root'
/ # fw_manager.sh -s &
/ # psvr ok,wait=1
fw_manager.sh revision: 2
pre-revision: 0
remove /data/lumi_fw
hostname: Aqara_Hub_E1-8213
type: lumi.gateway.aqcn02, model: AH_E1
Current platform: miot
Switch platform from miot to aiot
Backup hap_token_uuid and hap_token_key to '/res' succeed.`

but when I try to switch to aqara mode the hub keeps blinking red.

4. Writing this post to ask what am I missing and for some more help.

Thanks.

**Comment by rezmus** [comment]
what is current version of your fw? after switch cmd it should reset wifi, create ap and start to blink yellow.

**Comment by Cassiopea1** [comment]
FW version: 3.1.5_0020

Ooooooooooh, the "fw_manager.sh -s &" will switch to aqara mode, right? Maybe here was the problem, because I've done it manually on the hub...

**Comment by Cassiopea1** [comment]
Indeed the "fw_manager.sh -s &" command switched the hub to aqara mode, but after connecting to hub ap and telneting to it I've got again "Connection refused" or so.

**Comment by rezmus** [comment]
which ip do you telnet to? should be 192.168.49.1 iirc.

**Comment by Cassiopea1** [comment]
That's the one I've tried to connect to.

**Comment by niceboygithub** [comment]
> 2. If I switch to aqara mode and try to telnet into the hub I'm getting "No permission"

Did you have screenshot?

**Comment by rezmus** [comment]
also where you are in mijia mode run these cmds to confirm you have custom fw.
```
cat /bin/fw_manager.sh | grep riu_w
cat /bin/fw_manager.sh | grep telnetd
```

**Comment by Cassiopea1** [comment]
Thanks. I'll run them in the evening when I'm home.

**Comment by Cassiopea1** [comment]
Hi guys. My hub is now in the Aqara app. I've made a silly mistake. In the AP properties was listed my laptop's IP (192.168.49.100) and not the gateway one, so I tried to telnet to my laptop. Sorry for saying that I tried the 192.168.49.1 (I've seen 49 and I jumped to the conclusion that was the right one). And sorry for the extra trouble. Thanks again.

**Comment by jasonfonghk** [comment]
> get permanent root/telnet in mijia mode. switch to aqara mode
> 
> ```
> fw_manager.sh -s &
> ```
> 
> connect to hub ap, telnet to hub
> 
> ```
> asetprop persist.sys.model "lumi.gateway.aqcn03"
> reboot -f
> ```
hi brother, I have follow these commands in 2023, it's work,I still using it,thanks.

But I just buy a new E1 CN, follow the same steps, It's fail to add the E1 to EU server, even the model code change to lumi.gateway.aqcn03, it still can add to CN server.

Do you have a spare gateway to test these commands still work? or any new method? thanks.

**Comment by ARoussakov** [comment]
```
asetprop persist.sys.model "lumi.gateway.aqcn03"
reboot -f
```
Before this commands, switched to Aqara Mode with Aqara Home App, region China. And finally it works with Aqara D100 Lock.
