### ISSUE TITLE
Aqara Door Lock - H100 not shown on Aqara Gateway Integration

### ISSUE THREAD

**Issue by algovera** [niceboygithub/AqaraGateway#57]
I was able to open telnet and get access of aqara devices on HA
![image](https://user-images.githubusercontent.com/48702353/144528113-118e09ad-2381-4505-84c5-158b92b60593.png)

However, the Aqara Door Lock - H100, I am able to see it on Aqara App but not Aqara Gateway on HA.
![IMG_7639](https://user-images.githubusercontent.com/48702353/144528293-32c740dc-ed88-454a-93db-e0acb1d4c899.PNG)

Is there any fix or tweak available to get around this?
Thanks in advance

**Comment by niceboygithub** [comment]
H100 is not supported yet.
You can see [this isseue](https://github.com/niceboygithub/AqaraGateway/issues/37)
