### ISSUE TITLE
Aqara E1 gateway cannot start after using Not Flash Custom firmware method

### ISSUE THREAD

**Issue by zhxiaoping** [niceboygithub/AqaraGateway#58]
aqara E1 info
Name: Aqara Hub E1
Model: lumi.gateway.aqcn02

just like title said, after I finished procedure(using Not Flash Custom firmware method)
and reboot, E1 gateway siganl light is always yellow which means it get stuck with starting reffered to aqara guide book
Anybody can help me??

**Comment by niceboygithub** [comment]
need to UART to check what happened to this E1 hub.

**Comment by fuxy1999** [comment]
There is same question on my device. My aqara E1 stop working now. I reset the device after all flash done. Maybe something hapen on boot.

**Comment by niceboygithub** [comment]
unfortunately, if the led light keep yellow, it mean that it is bricked. Call Aqara Service.
