### ISSUE TITLE
problem with aqara double rocker WXKG02LM

### ISSUE THREAD

**Issue by shaokaollu** [niceboygithub/AqaraGateway#62]
I have problem with aqara double rocker WXKG02LM, this is what I get from HA. 
![2021-12-15 05_43_03-Developer Tools - Home Assistant](https://user-images.githubusercontent.com/38537984/146127534-23c4deb6-5602-4204-8c36-474d1bc3eacc.jpg).
I can finde only switch turned on and turned off in automation. I don't know how to select between left and right, short press, long press ect etc.

**Comment by dronix27** [comment]
> I have problem with aqara double rocker WXKG02LM, this is what I get from HA. ![2021-12-15 05_43_03-Developer Tools - Home Assistant](https://user-images.githubusercontent.com/38537984/146127534-23c4deb6-5602-4204-8c36-474d1bc3eacc.jpg). I can finde only switch turned on and turned off in automation. I don't know how to select between left and right, short press, long press ect etc.

You can use States of binary_sensor: button_1_single, button_2_single in Automation
