### ISSUE TITLE
Unable to add Aqara M1S 2022 lumi.gateway.acn004, Please Help!

### ISSUE THREAD

**Issue by Double-Dude** [niceboygithub/AqaraGateway#66]
I followed the instruction and spent 10 hours, but couldn't get it working.

Firstly, I've used the enable telnet command of both way 2 and way 3, it said "Ok":

<img width="643" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/12950464/147513824-abda0e00-b595-406d-9f28-d3947ad7ab69.png">

Then, I've tried to telnet with following combination of credentials, but none of them working:

username:   password:
admin           
admin           admin
admin           123123
admin           root

<img width="438" alt=" telnet 192 168 86 29" src="https://user-images.githubusercontent.com/12950464/147513936-22a0aac6-8d3b-4ece-9d6c-1dffd2fb117c.png">

Eventually I have to use username "root" and it seemed to be working(it didn't ask me password)? Not quite sure, please see the image below.

I tried to use the following script after using "root" to login:

```
mkdir /data/bin
cd /data/bin
wget -O /data/bin/curl "http://master.dl.sourceforge.net/project/mgl03/bin/curl?viasf=1"
chmod +x /data/bin/curl
/data/bin/curl -s -k -L -o /data/bin/mosquitto https://raw.githubusercontent.com/niceboygithub/AqaraM1SM2fw/main/binutils/mosquitto
chmod a+x /data/bin/mosquitto

mkdir /data/scripts
cd /data/scripts
/data/bin/curl -s -k -L -o /data/scripts/post_init.sh https://raw.githubusercontent.com/niceboygithub/AqaraM1SM2fw/main/binutils/post_init.sh
chmod +x /data/scripts/post_init.sh
```

**But it showed this error:**

/data/bin/curl: line 1: syntax error: unexpected "("

<img width="738" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/12950464/147513959-6ce9e727-f628-44d6-a2d8-c344e3e604d6.png">

I think that I am going to give up soon, not sure where it went wrong. :(

**Comment by niceboygithub** [comment]
1. M1S 2022 is not in the supported list.
2. the login name of M1S 2022 is root

M1S is using MIPSel , M1S 2022 is using Armv7, they are different CPU, the executable binary can not run on different CPU. So you see the error 'unexpected "("'.

M1S 2022 also change to use another Zigbee IC which use different architecture on zigbee message to miio. So it may not supported in this integration in the future.
