### ISSUE TITLE
M1s run at a 100% cpu usage, is it normal？

### ISSUE THREAD

**Issue by ruicai83** [niceboygithub/AqaraGateway#67]
Looks like it was installed incorrectly，the process “mha_basis” with a 99% cpu usage.

Mem: 46512K used, 76864K free, 0K shrd, 6080K buff, 22416K cached
CPU: 64.8% usr 34.9% sys  0.0% nic  0.0% idle  0.0% io  0.0% irq  0.1% sirq
Load average: 1.88 1.97 1.86 3/58 3889
  PID  PPID USER     STAT   VSZ  %VSZ CPU %CPU COMMAND
  950     1 admin    R     7568   6.1   0 98.8 mha_basis
 1043     1 admin    S     1632   1.3   0  0.2 {app_monitor.sh} /bin/sh /bin/app_monitor.sh
 2652  1170 admin    R     1584   1.2   0  0.2 top
  943     1 admin    S     1408   1.1   0  0.2 mdnsd
 1003     1 admin    S    11744   9.5   0  0.0 homekitserver -S
  969     1 admin    S    11696   9.4   0  0.0 mha_master
  975     1 admin    S     6464   5.2   0  0.0 mijia_automation -d /data/miio

**Comment by niceboygithub** [comment]
Did you try to reboot?

**Comment by ruicai83** [comment]
> 

Thanks for ur reply.
both m1s and homeassistant are rebooted。 when  unplug and plug the m1s , telnet m1s ,cpu usage work proper, but can't control the equipment by ha.

**Comment by niceboygithub** [comment]
To control sub devices, mqtt need to work properly.

Can you check the mosquito is running as public?

**Comment by ruicai83** [comment]
it work,thanks a lot!
