### ISSUE TITLE
should i upgrade?

### ISSUE THREAD

**Issue by chikehe** [niceboygithub/AqaraGateway#68]
im currently running m1s on firmware 3.1.4_0040, is it save to upgrade to new firmware 4.x.x? or will i loose integration connectivity?

**Comment by niceboygithub** [comment]
I do not get notify to update to firmware 4.x.x. I have no answer for you now.
If I flashed firmware 4.x.x, I will test it as soon as possible .

**Comment by chikehe** [comment]
> 

the upgrade notification disappeared here too, i now get upgrade for 3.1.6

**Comment by niceboygithub** [comment]
The firmware version 4.0.1 in Mi Home was uploaded.
Still works with AqaraGateway
