### ISSUE TITLE
how to open aqarq p3 telnet

### ISSUE THREAD

**Issue by mikeinblue** [niceboygithub/AqaraGateway#7]
Is there anyone can tell me how to use the custom open telnet command,thank you!

**Comment by xStars** [comment]
Open Aqara P3 telnet can use python-maiio.
```bash
miiocli gateway --ip xxx.xxx.xxx.xxx --token xxxxxxx raw_command set_ip_info '{"ssid":"\"\"","pswd":"123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd"}'
```
Replace xxx with your ip and token

**Comment by mikeinblue** [comment]
> Open Aqara P3 telnet can use python-miio
> 
> ```shell
> miiocli gateway --ip xxx.xxx.xxx.xxx --token xxxxxxx raw_command set_ip_info '{"ssid":"\"\"","pswd":"123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd"}'
> ```
> 
> Replace xxx with your ip and token

Thanks I will have a try.

**Comment by mikeinblue** [comment]
This gateway hasn't support mihome right now .So I can't get its token.

**Comment by xStars** [comment]
1. Press the button 10 times in a row
2. P3 will give a sound prompt to restore the factory setting successfully.
3. Then quickly contact and press the button twice.
4. If successful, you will hear a ringtone. restart，then Pressing the button for 5 seconds will prompt you to open Mi home app pairing.

**Comment by mikeinblue** [comment]
> * Press the button 10 times in a row
> * P3 will give a sound prompt to restore the factory setting successfully.
> * Then quickly contact and press the button twice.
> * If successful, you will hear a ringtone. restart，then Pressing the button for 5 seconds will prompt you to open Mi home app pairing.

thank you so much.I will have a try.

**Comment by mikeinblue** [comment]
finally,I solved it.Thanks for your great work.
![Screenshot_20210531-231650__01](https://user-images.githubusercontent.com/62834868/120214057-83e1d400-c266-11eb-9ea6-1838fc7c117b.jpg)

**Comment by xquyan** [comment]
> Open Aqara P3 telnet can use python-miio
> 
> ```shell
> miiocli gateway --ip xxx.xxx.xxx.xxx --token xxxxxxx raw_command set_ip_info '{"ssid":"\"\"","pswd":"123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd"}'
> ```
> 
> Replace xxx with your ip and token

I tried this command but got this error:

WARNING:miio.device:Found an unsupported model 'lumi.aircondition.acn05' for class 'Gateway'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
ERROR:miio.miioprotocol:Got error when receiving: timed out
Error: No response from the device

what can I do?
