### ISSUE TITLE
Aqara bridge

### ISSUE THREAD

**Issue by jscherry** [niceboygithub/AqaraGateway#71]
I was trying to set up the bridge and did as follows to apply for a developer account. I was able to register and log in but I'm stuck at the next screen? What or how do I obtain an id card number? Is contact just asking for a phone number? Any help is greatly appreciated.

Developer type
 Enterprise developer Personal developer
Individual developers are targeted at natural persons who are not for profit, including geeks, rice flour, etc.
Real name
Please enter the real name

ID card number

Contact

**Comment by niceboygithub** [comment]
I am not from Lumi(Aqara). I have no answer for you.
You need to finish application to get developer account. Please contact Aqara.
