### ISSUE TITLE
Add support for Smart Wall Switch H1 (lumi.switch.2acn)

### ISSUE THREAD

**Issue by firesunCN** [niceboygithub/AqaraGateway#73]
Hello,
Thanks for this amazing project. Could you please add support for the Smart Wall Switch H1 ?
lumi.switch.2acn
lumi.switch.1acn1
lumi.switch.cn1
lumi.switch.acn1
lumi.switch.3acn1

I used Aqara Home mode and could not discover this device.

**Comment by niceboygithub** [comment]
Can you help to get the logs?

**Comment by firesunCN** [comment]
I fixed it in this pr
https://github.com/niceboygithub/AqaraGateway/pull/75
