### ISSUE TITLE
M1S Unsupported command for color set command

### ISSUE THREAD

**Issue by VikeDragon** [niceboygithub/AqaraGateway#76]
Hi, after last update 0.0.11 - some warnings.
M1S in Mi Home mode firmware version 4.0.1_0012 :

Logger: custom_components.aqara_gateway.core.gateway
Source: custom_components/aqara_gateway/core/gateway.py:549
Integration: Aqara Gateway (documentation, issues)
First occurred: 22 января 2022 г., 21:53:23 (112 occurrences)
Last logged: 21:24:20

Unsupported cmd: {'cmd': 'control', 'data': {'blue': 0, 'breath': 500, 'green': 0, 'red': 0}, 'type': 'rgb', 'rev': 1, 'id': 7249}
Unsupported cmd: {'cmd': 'control', 'data': {'blue': 255, 'breath': 500, 'green': 255, 'red': 255}, 'type': 'rgb', 'rev': 1, 'id': 15508}
Unsupported cmd: {'cmd': 'control', 'data': {'blue': 0, 'breath': 500, 'green': 0, 'red': 0}, 'type': 'rgb', 'rev': 1, 'id': 39435}
Unsupported cmd: {'cmd': 'control', 'data': {'blue': 255, 'breath': 500, 'green': 255, 'red': 255}, 'type': 'rgb', 'rev': 1, 'id': 32261}
Unsupported cmd: {'cmd': 'control', 'data': {'blue': 0, 'breath': 500, 'green': 0, 'red': 0}, 'type': 'rgb', 'rev': 1, 'id': 7691}

I used script to turn on light of M1S:

  action:
    - service: light.turn_on
      target:
        entity_id: light.0x54ef44100005f389_rgb_color #<-- M1S entity light
      data:
        brightness: 255
        rgb_color: [255,255,255] #<-- for white color

I used script to turn off light of M1S:

  action:
    - service: light.turn_off
      target:
        entity_id: light.0x54ef44100005f389_rgb_color #<-- M1S entity light
      data:
        transition: 2

**Comment by VikeDragon** [comment]
Problem not solved

**Comment by VikeDragon** [comment]
Not solved core-2022.5.5

Logger: custom_components.aqara_gateway.core.gateway
Source: custom_components/aqara_gateway/core/gateway.py:563
Integration: Aqara Gateway (documentation, issues)
First occurred: 08:46:26 (2 occurrences)
Last logged: 09:01:23

Unsupported cmd: {'cmd': 'control', 'data': {'blue': 0, 'breath': 500, 'green': 0, 'red': 0}, 'type': 'rgb', 'rev': 1, 'id': 26431}
Unsupported cmd: {'cmd': 'control', 'data': {'blue': 0, 'breath': 500, 'green': 0, 'red': 0}, 'id': 17665, 'type': 'rgb', 'ver': 1}

**Comment by VikeDragon** [comment]
Not solved core-2022.8.1

Logger: custom_components.aqara_gateway.core.gateway
Source: custom_components/aqara_gateway/core/gateway.py:477
Integration: Aqara Gateway (documentation, issues)
First occurred: 12:24:32 (55 occurrences)
Last logged: 20:32:20

Unsupported cmd: {'cmd': 'control', 'data': {'blue': 0, 'breath': 500, 'green': 0, 'red': 0}, 'type': 'rgb', 'rev': 1, 'id': 36082}
Unsupported cmd: {'cmd': 'control', 'data': {'blue': 255, 'breath': 500, 'green': 255, 'red': 255}, 'type': 'rgb', 'rev': 1, 'id': 29485}
Unsupported cmd: {'cmd': 'control', 'data': {'blue': 0, 'breath': 500, 'green': 0, 'red': 0}, 'type': 'rgb', 'rev': 1, 'id': 10262}
Unsupported cmd: {'cmd': 'control', 'data': {'blue': 255, 'breath': 500, 'green': 255, 'red': 255}, 'type': 'rgb', 'rev': 1, 'id': 8678}
Unsupported cmd: {'cmd': 'control', 'data': {'blue': 0, 'breath': 500, 'green': 0, 'red': 0}, 'type': 'rgb', 'rev': 1, 'id': 24341}

**Comment by niceboygithub** [comment]
Please use master branch to test

**Comment by VikeDragon** [comment]
I installed master - but the errors are the same

**Comment by TempleZhou** [comment]
same issue
