### ISSUE TITLE
Would someone be kind enough to document how to open the M2 hub? 

### ISSUE THREAD

**Issue by DolfLund** [niceboygithub/AqaraGateway#77]
It's great that a photo exists of the board and solder points - but how does one open it? I peeled the sticker of the bottom, and found no screw holes. Is there a spot where I need to pry it apart? I'd rather not break the plastic to find out. 

Thanks for any guidance.

Also - the 3 wires mentioned do not contain 3 or 5V , am I to assume I should leave the device connected to wall power during flash?

thx

**Comment by rezmus** [comment]
use thin knife and put from top verticaly just next to edge.

**Comment by niceboygithub** [comment]
> It's great that a photo exists of the board and solder points - but how does one open it? I peeled the sticker of the bottom, and found no screw holes. Is there a spot where I need to pry it apart? I'd rather not break the plastic to find out.
> 
> Thanks for any guidance.

This is a example to open Xiaomi Multmode Gateway(mgl03).

https://youtu.be/5D8RARdUzPw

The plastic may get a little damage.

> Also - the 3 wires mentioned do not contain 3 or 5V , am I to assume I should leave the device connected to wall power during flash?
> 

You need plug in USB cable to power up it

**Comment by devincody** [comment]
Here's a pic of a disassembled M2 hub. You can see the clasps that you have to undo on the top of the hub:
https://imgur.com/a/yt5KpCM
