### ISSUE TITLE
Trigger alarm for Aqara M1S

### ISSUE THREAD

**Issue by xAlexV** [niceboygithub/AqaraGateway#79]
Hi,
I've recently moved my automation from HomeKit to home assistant.
I have all my Aqara devices connected via conbee 2, so no problems there.

But I also have a hub (Aqara M1S) which I tried to get it up and running in HA (not via HomeKit controller integration). I've managed to do that (as I can see in the HA information):
```
Aqara Gateway
Telnet Logged | xxx.xxx.xxx.171
MQTT Connected | xxx.xxx.xxx.171
```

I can also arm/disarm the alarm without any problems.

But my issues starts when I try to trigger the alarm. I cannot find any default services generated by the integration (as you do with the [Xiaomi Gateway (Aqara)](https://www.home-assistant.io/integrations/xiaomi_aqara/)).

So my question is, is there any way to have an automation that triggers the alarm from M1S? If not, are there any plans to integrate that in a next build?

Sorry if this question was already asked (i've seen another issue opened related to this, but not quite understood the outcome).

Cheers,
Alexandru

**Comment by niceboygithub** [comment]
it is not supported.
