### ISSUE TITLE
Instruction clarification? 

### ISSUE THREAD

**Issue by dasb00ter** [niceboygithub/AqaraGateway#80]
Looks active here so hopefully somebody can answer. I just received new m1s and aqara E1 blind motor. I am trying to follow the directions. 
I understand that I need to open telnet on the m1s. Does this HACS integration do that once I have retrieved and given it the token?

I read here https://gist.github.com/InsaneWookie/1221cd6267745ea3c16f6a2a83ba3a44 : 
"niceboygithub commented on Jun 20, 2021
Thanks, for your instructions.

I already added the feature to enable telnet in the integration to simply the instructions. Cause install php-miio library or python-miio for Windows User is not convenient. So if user provides token in the settings, it will try to enable telnet."

Thanks for clarification Im just having trouble following along

**Comment by shift-del1** [comment]
Yes, this integration enables telnet, but you have to follow the instructions on the home page to make it permanent.

**Comment by dasb00ter** [comment]
Thanks for your prompt reply! Ok that was great that it does that and enables telnet. So I have got my token and setup the integration. I have used putty to telnet in to the m1s. admin was the user, I think. Shows rlx linux insignia. 
So from there I have to follow the custom firmware instructions and I am done? Is that correct? Sorry for asking just dont really want to wait another 2 months for hub to arrive if I brick

**Comment by shift-del1** [comment]
You can follow the instructions here if you want to use a modded FW: Flash M1S Custom firmware method
Or you can follow the Not flash section of M1S if you don't plan to use Aqara Home. By the way, I bricked my M1S EU (requires a more complicated method as the ones on the home page refers to M1S CN), but ordered some tools and fixed it. With my M1S CN, I had no problem (used the Flash M1S Custom firmware method due to my need for Aqara Home).

**Comment by dasb00ter** [comment]
I went a head and ran the command to flash. I was worried that the m1s would upgrade itself to a newer firmware that might block the altered firmware. I have the CN version and all seems to be well. I mean who even wrote the altered firmware lol. I actually thought i might need to use to use the aqara app bc the blind motor is aqara but low and behold the aqara blind motor paired into the MI home app. 

Too tell you the truth I am not sure why I did this procedure which is odd for me lol. There are so many ways to do this and the aqara and mi smart ecosystems are so confusing at times. I really want this to be fully functional in Home Assistant but it would be nice if I could win over my wife who is an avid Iphone user. There is the whole homekit aspect and its integration too. I just had the feeling that well this might be the best way forward. Gotta factor in the wife/husband happy factor.

I will close the issue tomorrow but leave it open if you want to expand my knowledge but as of now really really thanks

**Comment by shift-del1** [comment]
Happy to read you managed to reach your goal. The situation is the same here, Android husband vs. iPhone wife, bad luck I'm the engineer :-) I also choose to have Home Assistant togerher with the original cloud solution (Mi Home/Aqara Home) as a backup. Enjoy your setup.

**Comment by shift-del1** [comment]
You just run the same commands and they will pick  the latest modified FW available. At least this is what I did and it worked.

**Comment by dasb00ter** [comment]
Thanks
