### ISSUE TITLE
Fail to add Aqara Camera Hub G3

### ISSUE THREAD

**Issue by dronix27** [niceboygithub/AqaraGateway#81]
Setup Fails "aborted. Telnet is opened and working. EU VERSION (CH-H03)

**Comment by niceboygithub** [comment]
What is the model number of EU version?

**Comment by dronix27** [comment]
> What is the model number of EU version?

CH-H03

**Comment by dronix27** [comment]
Logger: homeassistant.util.async_
Source: util/async_.py:144
First occurred: 17:34:10 (1 occurrences)
Last logged: 17:34:10

Detected blocking call inside the event loop. This is causing stability issues. Please report issue to the custom component author for aqara_gateway doing blocking calls at custom_components/aqara_gateway/core/shell.py, line 79: time.sleep(.1)

**Comment by dronix27** [comment]
> What is the model number of EU version?

lumi.camera.gwpagl01

**Comment by dronix27** [comment]
I have added the model number for the EU version to the utils.py file
'lumi.camera.gwpgl1': ["Aqara", "Camera Hub G3", "CH-H03"],
And now the camera was added without problems!
