### ISSUE TITLE
Aqara Gateway M1S Rgb Color cannot be controlled.

### ISSUE THREAD

**Issue by Djydpp** [niceboygithub/AqaraGateway#87]
No response after pressing the switch.

**Comment by Sol1in** [comment]
Same issue.
Device: lumi.dimmer.rcbac1 ZNDDMK11LM
Hub Aqara E1 with latest firmware (updated from modified repository)
I see that Power metric is working properly (others are not available).

**Comment by niceboygithub** [comment]
Can you try the master branch?

**Comment by littlehi** [comment]
> Device: lumi.dimmer.rcbac1 ZNDDMK11LM

Same issue, Device: lumi.dimmer.rcbac1
