### ISSUE TITLE
Aqara Door Locker P100 support

### ISSUE THREAD

**Issue by niceboygithub** [niceboygithub/AqaraGateway#9]
model: ZNMS19LM

**Comment by niceboygithub** [comment]
Add [Basic](https://github.com/niceboygithub/AqaraGateway/commit/6f3962d463b3fcf5686ece06c53765f6b1caa676) support.

**Comment by telanxu** [comment]
Thanks for your great efforts, I use M1S only for P100 lock and Aqara 3 button switch D1.
I am wondering, if I want to get basic support for P100, what should I do?
 Scenario 1: Change M1s to Mijia mode, and just enable telnet and copy Mqtt w/o installing your modified firmware? and change back to Aqara home mode?

or Scenario 2: Change M1s to Mijia mode, and just enable telnet and flash your modified firmware, then change back to Aqara home mode?

which one is right? or any suggestions? (based on my understanding, P100 can not be added into Mijia app, only Aqara home app)

Thanks in advance.

**Comment by niceboygithub** [comment]
> which one is right? or any suggestions? (based on my understanding, P100 can not be added into Mijia app, only Aqara home app)
> 
> Thanks in advance.

both scenario are right.
But I suggest use scenario 2.
Scenario 2 work more stable than scenario 1.

BTW, P100 works with G2H and M2.
