### ISSUE TITLE
Aqara FP1Presence Detector FP1 class should be 'occupancy',not 'motion'

### ISSUE THREAD

**Issue by casatift** [niceboygithub/AqaraGateway#90]
As the title , the FP1 Presence Detector FP1 correct class type is 'occupancy' not 'motion'.
now use 'motion' type sensor state in ha will auto off at 90 secs. but the sensor actual state could be on. or within 90secs the sensor actual state is off,but the ha state still shows on.

thanks

**Comment by casatift** [comment]
> https://bbs.hassbian.com/forum.php?mod=viewthread&tid=15621&page=1#pid436967

我就是CT……，只是建议作者在下一版直接修复

**Comment by niceboygithub** [comment]
Thanks, 

Please try the latest release.
