### ISSUE TITLE
Feature quest: add way to manually play audio- trigger alarm

### ISSUE THREAD

**Issue by thomdall** [niceboygithub/AqaraGateway#91]
Hello,
Is it possible to find a way to manually play built in audio such as xiaomi_aqara.play_ringtone in https://www.home-assistant.io/integrations/xiaomi_aqara/?
Much appreciated!

**Comment by niceboygithub** [comment]
It is difficult to support several gateways/hubs with this feature.

**Comment by rustybakra** [comment]
Hi niceboygithub,
Is there any way to use ringtone or play some alram using Automation. 
I am running your integration to use HA . 
I need to play an alarm on a trigger. Eg, On a door left open play Police car 1 Alarm. How do i do this from HA
