### ISSUE TITLE
unable to add ac Companion P3

### ISSUE THREAD

**Issue by xquyan** [niceboygithub/AqaraGateway#92]
I got the token and tried adding directly to the integration with no luck, giving the debug info below. I also tried the soft_hack to open telnet but no luck either. XiaomiGateway3 said unsupported device and python-miio got "no response from device" and "unsupported device lumi.aircondition.acn05", which is on their device list. Didn't try the php miio tho, setting up php was a bit trouble, and I expected it to work similar to python-miio.

Model: lumi.aircondition.acn05
Hardware version: Linux
Firmware version: 4.0.1_0001

DEBUG  main  SysInfo: {'installation_type': 'Home Assistant OS', 'version': '2022.3.8', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.9.9', 'docker': True, 'arch': 'x86_64', 'os_name': 'Linux', 'os_version': '5.10.103', 'user': 'root', 'supervisor': '2022.03.5', 'host_os': 'Home Assistant OS 7.5', 'docker_version': '20.10.9', 'chassis': 'embedded'}
ERROR  gateway  Failed to connect to MQTT server 192.168.18.53 due to exception: [Errno 111] Connection refused

what can I do?

**Comment by niceboygithub** [comment]
downgrade the firmware.

**Comment by xquyan** [comment]
> downgrade the firmware.

thx for reply! It worked out later so the firmware seems supported. My problem seemed python related, got it to work on another computer. Couldn't figure out what's wrong with my python install though

**Comment by hncdjzw** [comment]
请问如何降级？
