### ISSUE TITLE
Aqara P3 energy component

### ISSUE THREAD

**Issue by seanzhang98** [niceboygithub/AqaraGateway#99]
Wondering if there any way to get the power consumption data from the P3？
THX

**Comment by niceboygithub** [comment]
if P3 is in mi home mode, it is possible to get power consumption data vai miio

**Comment by seanzhang98** [comment]
@niceboygithub so it is impossible to obtain the power consumption data with AIOT?

**Comment by niceboygithub** [comment]
With my limited knowledge on P3, it can not get power consumption data in AIOT mode.
Maybe need to dig more deeper in AIOT mode.
